Вопросы Коровкин
BaldiSlayer/rofl-lab1 pull request #100
Opened 2024-11-13 19:57 UTC by alexgroga

2024-11-13 20:20 UTC, BaldiSlayer commented
откати изменения `json` пж, они нам не нужны, он депрекейтед)) оставили пока не перенесем все вопросы

2024-11-13 20:24 UTC, BaldiSlayer commented on data/data.yaml
> +    Для этого можно использовать CYK-алгоритм (алгоритм Кока-Янгера-Касами), представляющий собой эффективный метод проверки принадлежности цепочки к контекстно-свободному языку. Он начинается с грам
я уже вижу, как этот вопрос будет нам выпадать как похожий для языка Дика 😀

2024-11-13 20:39 UTC, BaldiSlayer commented on data/data.yaml
> +    Пусть G имеет длину n. Тогда у нее может быть порядка n нетерминалов, и каждый проход индуктивного обнаружения порождающих нетерминалов может занимать O(n) времени для проверки всех продукций G.
давай тут тоже напишем что такое G

2024-11-14 03:13 UTC, TonitaN requested changes
Нужно аккуратно проверить на дубли, один ответ входит в другой, его убрать, и уточнить остальные.

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Порождения из стартового символа грамматики приводят к цепочкам, которые называются 'выводимыми цепочками' ('sentential form'). Пусть G = (V, T, P, S) — контекстно-свободная грамматика, где V — м
Ещё раз подчеркнуть в конце разницу между элементами языка грамматики и сентенциальными формами. Что такое lm, rm - расшифровать словами.

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Порождения из стартового символа грамматики приводят к цепочкам, которые называются 'выводимыми цепочками' ('sentential form'). Пусть G = (V, T, P, S) — контекстно-свободная грамматика, где V — м
T лучше заменить на Sigma (здесь и далее), а V на N, чтобы было как у всех

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Цепочка 𝜔 имеет два разных дерева разбора тогда и только тогда, когда 𝜔 имеет два разных левых порождения из P.
В каких случаях, если это выполняется, грамматика считается неоднозначной? Добавить

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Пусть G = (V, T, P, S) — контекстно-свободная грамматика, где V — множество нетерминалов, T — терминалов, P — множество продукций, S — стартовый символ. Если рекурсивный вывод утверждает, что тер
Почему рекурсивный вывод должен утверждать это? А если я пользуюсь не рекурсивным алгоритмом, что-то поменяется в ответе?

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Если контекстно-свободная грамматика 𝐺1 строится из грамматики G путем удаления цепных продукций, то 𝐿(𝐺1) = 𝐿(𝐺), где L - контекстно-свободный язык, порожденный грамматикой G.
Расшифровать словами.

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Если L - контекстно-свободный язык и h - гомоморфизм, то обратный гомоморфизм h(L)^-1 также является контекстно-свободным языком.
Пояснить с примером, что такое обратный гомоморфизм языка.

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Контекстно-свободные языки замкнуты относительно подстановки, объединения, конкатенации, обращения и обратного гомоморфизма. Контекстно-свободные языки не замкнуты относительно пересечения и допо
А прямого гомоморфизма? И этот вопрос вбирает в себя вопрос выше, что не очень хорошо с т.з. нахождения ближайших контекстов. Лучше тогда вопрос выше вовсе убрать и заменить чем-нибудь ещё.

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Как эффективно проверить принадлежность цепочки 𝜔 контекстно-свободному языку L?
Почему только CYK-ом в ответе? Есть ещё минимум Эрли, не считая всяких GLR, GLL алгоритмов.
Или уж сказать, что CYK переносится ещё и на некоторые классы КЗ-грамматик, или упомянуть его в вопросе. И расшифровать по-английски, да)

2024-11-14 03:13 UTC, TonitaN commented on data/data.yaml
> +    Пусть G имеет длину n. Тогда у нее может быть порядка n нетерминалов, и каждый проход индуктивного обнаружения порождающих нетерминалов может занимать O(n) времени для проверки всех продукций G.
И тут же вопрос - а что, лучше, чем квадратично, нельзя?

2024-11-14 14:36 UTC, alexgroga commented
Добрый вечер, Антонина Николаевна @TonitaN! Исправил ваши замечания. Изменил формулировку вопроса про CYK (упомянул название в вопросе с добавлением перевода). Вопрос про гомоморфизм убрал и добавил новый вопрос

2024-11-14 19:52 UTC, BaldiSlayer commented
Каж ты забыл для алгоса Кока Янгера Касами https://github.com/BaldiSlayer/rofl-lab1/pull/100#discussion_r1841130569

Можешь просто написать, что можно эту идею применить, а не как именно

2024-11-14 19:57 UTC, BaldiSlayer commented on data/data.yaml
> +    Если L - контекстно-свободный язык, а R - регулярный язык, то что можно сказать про их пересечение?
Строго говоря этот вопрос входит в следующий

2024-11-17 19:50 UTC, molivka commented on data/data.yaml
> +    Что такое нормальная форма Хомского?
крайне близко с точки зрения смысла с вопросом @sprosonya «Какой смысл нормальной формы Хомского?»

2024-11-17 19:52 UTC, molivka commented on data/data.yaml
> +    Если L - контекстно-свободный язык, а R - регулярный язык, то что можно сказать про их пересечение?
дубль @papashik «Замкнуты ли контекстно-свободные языки относительно операции 'пересечение с регулярным языком'?»

2024-11-17 19:52 UTC, molivka commented on data/data.yaml
> +    Если L - контекстно-свободный язык, а R - регулярный язык, то их пересечение является контекстно-свободным языком.
аналогично вопросу выше

2024-11-17 19:58 UTC, molivka commented on data/data.yaml
> +    Пусть G - контекстно-свободная грамматика, язык которой содержит хотя бы одну непустую цепочку. Можно ли построить грамматику G1 в нормальной форме Хомского такую, что язык грамматики G1 совпадет
дубль по смыслу с @papashik «Докажи, что любую контекстно-свободную грамматику можно привести к нормальной форме Хомского.»

2024-11-17 20:28 UTC, sprosonya commented on data/data.yaml
> +    Что такое нормальная форма Хомского?
Я видела этот Лешин вопрос и мне кажется, что они по смыслу разные. Один отвечает на вопрос, какие именно ограничения на КС-грамматику задает НФ Хомского, а другой разъясняет, какие преимущества дает использование этой НФ при работе с КС-грамматиками
Конечно, при желании можно слить эти два вопроса в один, но мне кажется, что они все-таки про разное

2024-11-18 11:26 UTC, molivka commented on data/data.yaml
> +    Что такое нормальная форма Хомского?
окей)
пока у нас нет понимания как правильно сравнивать на ближайшие: вопрос с вопросом юзера / вопрос + ответ с вопросом юзера и тд, я оставляю такие комменты

2024-11-18 11:35 UTC, BaldiSlayer commented on data/data.yaml
> +    Что такое нормальная форма Хомского?
> Я видела этот Лешин вопрос и мне кажется, что они по смыслу не сильно близки. Один отвечает на вопрос, какие именно ограничения на КС-грамматику задает НФ Хомского, а другой разъясняет, какие преимущества дает использование этой НФ при работе с КС-грамматиками Конечно, при желании можно слить эти два вопроса в один, но мне кажется, что они все-таки про разное

строго говоря это будет очень сильно зависеть от поиска близких))))))

2024-11-28 12:03 UTC, alexgroga commented
@TonitaN посмотрите мои исправления, пожалуйста

2024-11-28 23:10 UTC, TonitaN requested changes

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Может ли цепочка 𝜔, порожденная контекстно-свободной грамматикой G = (N, Σ, P, S), иметь два разных дерева разбора, если у нее только одно левое порождение из P? Σ — множество терминальных символ
Тут спецсимволы в вопросе ничего не проясняют, но написано аккуратно, для пробы можно и оставить.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Пусть G = (N, Σ, P, S) — контекстно-свободная грамматика, где N — множество нетерминалов, Σ — терминалов, P — множество продукций, S — стартовый символ. Если терминальная цепочка w принадлежит яз
Лучше чуть-чуть пояснить про крону, как она вычисляется. И добавить её английские названия.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Пусть G = (N, Σ, P, S) — контекстно-свободная грамматика, где N — множество нетерминалов, Σ — терминалов, P — множество продукций, S — стартовый символ. Если терминальная цепочка w принадлежит яз
Опечатка

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Грамматикой в нормальной форме Хомского (англ. Chomsky normal form) называется контекстно-свободная грамматика, в которой могут содержаться правила только следующего вида: A→BC; A→a; S→ε, где a —
Халявно, но уж пусть остаётся. Только дополнительно поясните словами, какие ограничения на правила.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    CYK-алгоритм (Cocke–Younger–Kasami algorithm) представляет собой эффективный метод проверки принадлежности цепочки к контекстно-свободному языку. Он начинается с грамматики в нормальной форме Хом
Тут сокращение НФХ, которого не было выше у вас же. Уж лучше в скобках англ.термин дать. 
Я не вижу, зачем тут вообще нужно вводить обозначения \alpha_i. А главное, ответ на вопрос некорректный: тут ни слова о том, как работает алгоритм, - только о его сложности.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Какое время требуется для поиска всех порождающих символов в контекстно-свободной грамматике G?
Не думаю, что тут нужно это G

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Пусть G = (N, Σ, P, S) — контекстно-свободная грамматика, где N — множество нетерминалов, Σ — множество терминалов, P — множество продукций, и S — стартовый символ. Пусть длина G равна n. Тогда у
Пояснить, что такое длина грамматики.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Предположим, что мы уже обнаружили, что нетерминал — порождающий. Мы спускаемся по списку позиций в телах, содержащих этот нетерминал. Для каждой такой позиции счетчик продукции уменьшаем на 1. К
Какая связь? Тут неочевидно.

2024-11-28 23:10 UTC, TonitaN commented on data/data.yaml
> +    Пусть G - контекстно-свободная грамматика, язык которой содержит хотя бы одну непустую цепочку. Можно ли построить грамматику G1 в нормальной форме Хомского такую, что язык грамматики G1 совпадет
Почему такие странные исключения? Вопрос непонятен и вряд ли полезен, поскольку существует вообще любая грамматика в НФХ, язык которой совпадает с языком исходной, за исключением единственного слова.

2024-12-07 17:28 UTC, alexgroga commented
@TonitaN Добрый вечер! Постарался исправить ваши замечания и заменил последний вопрос. Посмотрите, пожалуйста

2024-12-08 13:31 UTC, BaldiSlayer commented
удали `.md` файл из `pr` плз)

2024-12-12 13:16 UTC, TonitaN commented on data/data.yaml
> +    Крона w (англ. leaves of the parse tree) вычисляется следующим образом: 1) для текущего нетерминала A, из которого нужно вывести w, выбирается продукция A → X_1X_2...X_k, где X_i - терминалы или
чаще - yield of a tree

2024-12-12 13:22 UTC, TonitaN commented on data/data.yaml
> +    CYK-алгоритм (Cocke–Younger–Kasami algorithm) представляет собой эффективный метод проверки принадлежности цепочки к контекстно-свободному языку. Он начинается с грамматики в нормальной форме Хом
+ Есть модификации CYK, не требующие НФХ, а требующие только отстутствия длинных правил. Они вычисляют эпсилон-замыкания и замыкания по цепным правилам на лету.

2024-12-16 00:11 UTC, TonitaN approved these changes

2024-12-16 00:15 UTC, BaldiSlayer commented
@alexgroga как решишь конфликты - зови, аппрувну

2024-12-19 15:20 UTC, BaldiSlayer commented
Ладно, сам так сам

2024-12-19 15:22 UTC, merged