feat: added telegram bot
BaldiSlayer/rofl-lab1 pull request #11
Opened 2024-09-28 19:21 UTC by BaldiSlayer

2024-09-28 23:05 UTC, BaldiSlayer commented on internal/app/tgbot/actpool/actpool.go
> +	mu sync.Mutex
Дописать, что локает этот `mutex`

2024-09-28 23:08 UTC, BaldiSlayer commented on internal/app/tgbot/controllers/kbase.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
magic const, почему именно 2 секунды?

2024-09-28 23:08 UTC, BaldiSlayer commented on internal/app/tgbot/beclient/mock.go
> +	return "пошел нахуй", nil
Надо поправить на что-то поприличнее

2024-09-28 23:08 UTC, BaldiSlayer commented on internal/app/tgbot/ustorage/ustorage.go
> +	SetState(userID int64, state models.UserState) error
Комментов докинуть бы

2024-09-29 09:42 UTC, BaldiSlayer commented on internal/app/tgbot/actpool/actpool.go
> +	b.actionsMutex.Lock()
Убрать `mutex`. У нас только операции чтения, `Race Condition` не будет. `AddController` не будет добавлять хэндлеры "на лету". Это странно

2024-09-29 10:02 UTC, BaldiSlayer commented on internal/app/tgbot/tgcommons/keyboard.go
> +func (bot *TGBotApp) deleteCommand(update tgbotapi.Update) error {
убрать

2024-09-29 10:24 UTC, stewkk requested changes

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/models/ustates.go
> +	TRSState
Тут коммент потерял =))))

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/tgbot.go
> +		// походу надо будет сюда еще воткнуть rate limiter
В апи либы такого нет? =(

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/tgcommons/keyboard.go
> +func (bot *TGBotApp) deleteCommand(update tgbotapi.Update) error {
оаоаоа. Удалим?

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/tgconfig/tgconfig.go
> +	Token string `env:"TGBOTOKEN"`
nitpick: `TGTOKEN`

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/ustorage/mstorage.go
> +// MapUserStorage хранилище данных о пользователе, которое использует map
nitpick: более идеоматично `MapUserRepository`

2024-09-29 10:24 UTC, stewkk commented on internal/app/tgbot/actpool/actpool.go
> +	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
Я бы этот код сделал не специфичным для бота. Типа пробрасывать взаимодействие с ботом как стратегию, и тогда можно сделать стратегию для взаимодействия через TUI и переиспользовать этот код (т.к. сценарий взаимодействия через консоль мог бы быть такой же).

Ну и в целом зависимость он конкретной либы так себе.

В целом можно это не править, т.к. для лабы ок

2024-09-29 10:26 UTC, stewkk commented on internal/app/tgbot/actpool/actpool.go
> +	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
Ну и + ко всему, можно было бы замокать стратегию и написать тесты на весь этот код =)

2024-09-29 10:26 UTC, BaldiSlayer commented on internal/app/tgbot/actpool/actpool.go
> +		actions: make(map[models.UserState]func(update tgbotapi.Update) (models.UserState, error)),
Я вот как раз не смог придумать имя и поэтому оставил, поправлю

2024-09-29 10:27 UTC, BaldiSlayer commented on internal/app/tgbot/models/ustates.go
> +	TRSState
не, я просто `TRSState` еще не делал, поэтому не дописано

2024-09-29 10:28 UTC, BaldiSlayer commented on internal/app/tgbot/tgcommons/keyboard.go
> +func (bot *TGBotApp) deleteCommand(update tgbotapi.Update) error {
да, я уже оставлял коммент на это выше

2024-09-29 10:31 UTC, BaldiSlayer commented on internal/app/tgbot/controllers/controller.go
> +// Controller служит для передачи данных в контроллеры
ну тут не совсем очевидно, да, но так как все контроллеры реализуются как методы для структуры `Controller`, то она служит для того, чтобы можно было удобно передавать параметры, общие для всех `controller`'ов, просто задавая их при создании объекта `Controller`

2024-09-29 11:25 UTC, stewkk commented on internal/app/tgbot/controllers/controller.go
> +// Controller служит для передачи данных в контроллеры
Ааааа, ты в этом смысле. Ну это как будто деталь реализации

2024-09-29 12:02 UTC, ark2016 reviewed
вроде норм, не сильно шарю в golang

2024-09-29 18:07 UTC, BaldiSlayer commented on internal/app/tgbot/tgbot.go
> +		// походу надо будет сюда еще воткнуть rate limiter
не знаю, потому посмотрим

2024-09-29 18:12 UTC, merged