Утебаева :(
BaldiSlayer/rofl-lab1 pull request #124
Opened 2024-11-29 22:08 UTC by molivka

от создателей «кофейку бахнем и норм»...
ps: за сегодня 4 кружки кофе и одна пуэра

2024-11-29 22:16 UTC, BaldiSlayer commented on data/data.yaml
> +   Если строка S удовлетворяет всем условиям φ_1, φ_2, ..., φ_n, то S удовлетворяем правилу A_i
```suggestion
   Если строка S удовлетворяет всем условиям φ_1, φ_2, ..., φ_n, то S удовлетворяет правилу A_i 
```

тут случайно не "т"?

2024-11-29 22:20 UTC, molivka commented on data/data.yaml
> +   Если строка S удовлетворяет всем условиям φ_1, φ_2, ..., φ_n, то S удовлетворяем правилу A_i
я есть грут...
да, «т»

2024-11-29 22:21 UTC, BaldiSlayer commented on data/data.yaml
> +    q_0 - стартовое состояние, δ: (Σ ∪ e) × Q -> Q, то есть, область определения функции перехода - это алфавит,
```suggestion
    q_0 - стартовое состояние, δ: (Σ ∪ ε) × Q -> Q, то есть, область определения функции перехода - это алфавит, 
```

пустое слово вроде везде как ε писали, го тут тогда тоже

2024-11-29 22:22 UTC, molivka commented on data/data.yaml
> +    q_0 - стартовое состояние, δ: (Σ ∪ e) × Q -> Q, то есть, область определения функции перехода - это алфавит,
ок

2024-11-30 15:29 UTC, BaldiSlayer commented on data/data.yaml
> +    Если существует натуральное k, такое, что значение функция f(n) оценивается как O(n^k),
```suggestion
    Если существует натуральное k, такое, что значение функции f(n) оценивается как O(n^k), 
```

кажется так

2024-11-30 15:29 UTC, BaldiSlayer commented on data/data.yaml
> +    Если существует натуральное k, такое, что значение функция f(n) оценивается как O(k^n),
```suggestion
    Если существует натуральное k, такое, что значение функции f(n) оценивается как O(k^n), 
```

и тут вроде тоже вот так

2024-11-30 15:36 UTC, BaldiSlayer commented on data/data.yaml
> +    Экспоненциальная неоднозначность возникает тогда, когда существует два различных пути из одного состояния автомата в другое.
хм, я мб туплю, но если более 2 различных путей, то тоже будет экспоненциальная недоднозначность же, да?

если да, то имхо это надо подчеркнуть написав
> хотя бы два 

или 
> 2 или более

2024-11-30 16:10 UTC, BaldiSlayer commented on data/data.yaml
> +    Какие языки обладают свойством беспрефиксности (prefix-free)?
btw их еще называют префиксными https://github.com/BaldiSlayer/rofl-lab1/pull/61#discussion_r1818200930

если честно мне вообще неочевидно почему называется одновременно и префиксным и беспрефиксным

для меня вне контекста этих языков `не префиксный = беспрефиксный`, каким образом это значит одно и то же..

2024-11-30 16:11 UTC, BaldiSlayer commented on data/data.yaml
> +    Пример: (x & y), где x и y - пропозициональные переменные, & - логическое «и»
я бы на всякий случай написал бы что такое `пропозициональные переменные`

2024-11-30 16:12 UTC, BaldiSlayer commented on data/data.yaml
> +    переменная является правильным алгебраическим выражением. Если A и B - правильные алгебраические выражения, и рассматриваем
кринжану и скажу, что не закрыта скобочка, которая стояла перед "то"

2024-11-30 16:22 UTC, molivka commented on data/data.yaml
> +    Если существует натуральное k, такое, что значение функция f(n) оценивается как O(n^k),
жесть...
прикол в том, что я проверяла на грамматические ошибки(

2024-11-30 16:22 UTC, BaldiSlayer commented on data/data.yaml
> +    Слово w допускается AFA (Alternating Finite Automaton) тогда и только тогда, когда существует путь
начиная с
> когда существует путь

я бы немного порефакторил "язык", мне имхо было тяжеловато читать из-за оБрАтНыХ сСыЛоК с помощью `то есть`, `что` 

Мой вариант

> Слово w допускается AFA (Alternating Finite Automaton) тогда и только тогда, когда существует путь q_0 -> q_1 -> ... -> q_n, причём слово из символов q_0q_1...q_n равно слову w, такой, что если q_i принадлежит Q_∀ (множеству конъюнктивных состояний), и конфигурация имеет вид <q_i, v_i> (то есть, осталось прочитать суффикс v_i), то v_i распознаётся по всем переходам из q_i.

но тут могу быть неправ)

2024-11-30 16:27 UTC, BaldiSlayer commented on data/data.yaml
> +    Важно не забыть про разбиение при котором все символы попадают в Σ_int - алфавит внутренних символов.
мб дописать, что если для всех разбиений построили бесконечную серию well matched, то тогда он не VPL? С одной стороны из контекста вроде понятно, но все же)

2024-11-30 16:28 UTC, BaldiSlayer commented on data/data.yaml
> +    Если существует натуральное k, такое, что значение функция f(n) оценивается как O(n^k),
нуу)
одну буковку всегда можно пропустить

2024-11-30 16:30 UTC, BaldiSlayer commented
в принципе прикольно, я тут еще наглядно увидел возможную пользу от твоей идеи строить для одного ответа несколько вопросов, на которые он может ответить

возможно стоит подумать над тем, чтобы сделать поле `question` массивом)

2024-11-30 17:53 UTC, molivka commented on data/data.yaml
> +    Экспоненциальная неоднозначность возникает тогда, когда существует два различных пути из одного состояния автомата в другое.
туплю я, ты прав. 
хотя бы два

2024-11-30 17:59 UTC, molivka commented on data/data.yaml
> +    Какие языки обладают свойством беспрефиксности (prefix-free)?
также задавалась этим вопросом, почему два противоположных по смыслу (в привычном понимании) обозначают одно и то же
в этом плане англ. версия лучше
я считаю, что не надо добавлять в скобках «префиксности», чтобы никого не запутать

2024-11-30 18:02 UTC, molivka commented on data/data.yaml
> +    Пример: (x & y), где x и y - пропозициональные переменные, & - логическое «и»
согл

2024-11-30 18:05 UTC, molivka commented on data/data.yaml
> +    Важно не забыть про разбиение при котором все символы попадают в Σ_int - алфавит внутренних символов.
считаю, что это лишнее

2024-11-30 18:16 UTC, BaldiSlayer commented on data/data.yaml
> +    Важно не забыть про разбиение при котором все символы попадают в Σ_int - алфавит внутренних символов.
ну ок)

2024-11-30 18:17 UTC, BaldiSlayer commented on data/data.yaml
> +    Какие языки обладают свойством беспрефиксности (prefix-free)?
ну окей, давай оставим ток один вариант

2024-11-30 23:48 UTC, TonitaN requested changes
Вопросы 🔥, осталось чуть уточнить теорию (заодно получается реальная подготовка к РК и экзамену).

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    Производная Бржозовски (Brzozowski derivative) языка L по слову u - это множество u^(-1)L = {w|uw ∈ L} слов,
Неплохо бы ещё добавить, что они же - частные по единственному слову, и когда идёт речь о регулярных выражениях, то их производная Брзозовски представляется уже не множеством, а единственной регуляркой (тонкость: есть производные Антимирова, они формируют множество регулярок). Причём тут есть "перегрев" термина: для просто формальных языков производная суть частное по слову, для регулярок - регулярка.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    то автомат A называется экспоненциально неоднозначным.
Не лишне добавить, что других видов неоднозначностей в конечных автоматах (NFA) нет.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    Экспоненциальная неоднозначность возникает тогда, когда существует два различных пути из одного состояния автомата в другое.
И забыли самое главное: пути читают одно и то же слово, и не в другое, а в себя же.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    между которыми существует путь по символу w, существуют петли (переходы в себя) по w.
Почему по символу? Мб и по слову. И тут поэтому лучше заменить петли на циклы

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    Совпадают ли классы языков, которые распознаются PDA (Pushdown Automata) c классом языков, которые
Классы языков друг с другом или класс языков с классом языков (знаю, душно, но надо)

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    1. Множество утверждений, состоящих из переменных, логических операций и скобок,
Очень важно: все эти примеры работают, только если _все_ операции заключаются во внешние скобки. Т.е. `(x & y)` ок, но `x & y` не ок, можно приписать ещё конъюнкт, и prefix-free свойство опровергнется.
Нужно подчеркнуть это, и поправить пример ниже с арифметикой, где про скобочки забыли.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    Лемма Ардена (Arden's rule): пусть X, Y, Z - регулярные выражения, X = YX | Z, где Z не зависит от X, пустое слово не принадлежит Y,
На самом деле Y, Z - любые языки, подходящие под прочие условия.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +   S - начальный символ, Δ - множество правил, назовём их A_i, таких, что они имеют вид: A_i -> φ_1 & φ_2 & ... & φ_n,
Можно удалить, назовём их A_i.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +   Если строка S удовлетворяет всем условиям φ_1, φ_2, ..., φ_n, то S удовлетворяем правилу A_i
Лучше "удовлетворяет правилу разбора A_i", т.к. тут всё-таки нетерминалы, а иначе они будут путаться с названиями правил, хотя у одного и того же нетерминала может быть много правил разбора, и в этих обозначениях они все будут называться одинаково.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    В правилах для всех терминалов конъюнкция не используется, так, правило A задаёт язык a^(*), где * обозначает итерацию
Для терминалов конъюнкция и не может использоваться, они же никуда не переписываются. Или я не так поняла это предложение?

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    второй конъюнкт - DC, определяет все строки вида a^(m)b^(m)c^(*), тогда, получается, что правило для S определяет строки a^(*)b^(*)c^(*),
Строки в языке a*b*c* - так точнее

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    все строки a^(*)b^(*)c^(*), которые содержат одинаковое количество символов a, b, c, а это есть a^(n)b^(n)c^(n)
в языке a*b*c*

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    S - начальный символ, Δ - множество правил, назовём их A_i. Конъюнктивная грамматика G находится в двоичном нормальном виде,
По аналогичным причинам, лучше не называть правила именами нетерминалов в их левых частях

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    Существует теорема, которая утверждает, что всякая грамматика над односимвольным алфавитом задаёт регулярный язык,
Всякая КС-грамматика. С конъюнктивными это уже не работает, там есть и не регулярные унарные языки.

2024-11-30 23:48 UTC, TonitaN commented on data/data.yaml
> +    2. Для каждого из разбиений A нужно попытаться построить бесконечную серию well matched (конгруэнция well matched слов w_1, w_2
Не совсем точно: конгруэнция определяется на словах u, v, которые сбалансированы (well-matched), т.е. структуры их символов вызова и возврата представляет собой ПСП (относительно единственного вида скобок: символы вызова все понимаются как (, возврата - как ). ).
А w1 и w2 - левый и правый контексты, они не обязаны быть сбалансированы. Конгруэнция говорит, что в любом контексте мы можем заменять сбалансированные слова из одного к.э. друг на друга без изменения свойства принадлежности языку.

2024-12-01 09:14 UTC, molivka commented on data/data.yaml
> +    В правилах для всех терминалов конъюнкция не используется, так, правило A задаёт язык a^(*), где * обозначает итерацию
я ошиблась, потеряла частицу «не» перед словом «терминалов»

2024-12-01 10:11 UTC, TonitaN commented on data/data.yaml
> +    В правилах для всех терминалов конъюнкция не используется, так, правило A задаёт язык a^(*), где * обозначает итерацию
Тогда ещё добавить: "кроме стартового, который не встречается в правых частях правил"

2024-12-12 13:37 UTC, TonitaN commented on data/data.yaml
> +    Частные производные Бржозовски (Brzozowski derivative)
Частные производные называются антимировскими, производные Бржозовски как раз собирают все производные Антимирова в одно выражение посредством операции объединения (альтернативы)

2024-12-12 13:37 UTC, TonitaN commented on data/data.yaml
> +    Лемма Ардена (Arden's rule): пусть X - регулярное выражение, Y, Z - произвольные языки, X = YX | Z, где Z не зависит от X,
X тоже не обязано быть регулярным выражением, в общем X,Y,Z - любые языки.
Т.е. если Y,Z - не регулярные, то X скорее всего тоже не регулярно, но выражается через них точно так же.
Пример: язык X = YX | c, где Y = {a^n b^n | n>0}. X есть {(a^ni b^ni)*c | ni>N и могут быть различны для разных итераций}. Y и X здесь --- КС, но зависимость по Ардену сохранена.

2024-12-12 13:37 UTC, TonitaN commented on data/data.yaml
> +    так, правило для A задаёт язык a^(*), где * обозначает итерацию Клини (Kleene star), правило для C, аналогично, задаёт язык c^(*),
А нужно ли так усложнять обозначение для итерации? Может, просто a*, как обычно пишут другие? Хотя не настаиваю.

2024-12-12 13:37 UTC, TonitaN commented on data/data.yaml
> +    Конгруэнция well matched означает, что в любом контексте можно заменять сблансированные слова (слова,
Можно упомянуть, что это конгруэнция по отношению эквивалентности Майхилла-Нероде.
И что well-matched слова в таком контексте могут рассматриваться как слова во внутреннем алфавите, поскольку не вовлекают никакой внешний стек (не имеют воздействия на стек после их прочтения). А число классов таких слов должно быть конечно, т.к. конечно число состояний VPA

2024-12-15 15:02 UTC, molivka commented
@TonitaN (тегаю на всякий случай)

2024-12-15 19:08 UTC, TonitaN approved these changes
Красиво.

2024-12-15 19:10 UTC, BaldiSlayer approved these changes
****

2024-12-15 19:38 UTC, merged