Лабораторная работа 5. Егорова Алиса
BaldiSlayer/rofl-lab1 pull request #157
Opened 2024-12-19 12:36 UTC by AlisaEee

2024-12-19 12:48 UTC, BaldiSlayer commented on data/data.yaml
> +    Дя, верно. Так как конъюктивные языки - языки, описываемые грамматиками, правила которых имеют вид A -> B1 & ... & B2.
```suggestion
    Да, верно. Так как конъюктивные языки - языки, описываемые грамматиками, правила которых имеют вид A -> B1 & ... & B2.
```

ониии чан

2024-12-19 13:12 UTC, molivka commented on data/data.yaml
> +    Что такое степень недетерминированности(неоднозначности) автомата?
повтор с моим вопросом, строка 1700 в yaml

2024-12-19 13:26 UTC, molivka commented on data/data.yaml
> +    Когда язык называется разрешимым?
у Миши Ф. был вопрос про рекурсивные (= разрешимые, насколько я поняла) языки, 219 строка в yaml, но там в другой формулировке, так что, думаю, ок, не повтор

2024-12-19 13:32 UTC, molivka commented
далее, на адекватность провалидирует @BaldiSlayer, он делает это лучше меня)

2024-12-19 14:58 UTC, BaldiSlayer commented on data/data.yaml
> +    Язык L называется разрешимым, если существует такая вычислимая функция f такая, что если w принадлежит L, то f(w) = 1 и, если w не принадлежит L, то f(w) = 0
1. два раза "такая")
один из них надо убрать 

2. что такое `w`?

2024-12-19 14:59 UTC, BaldiSlayer commented on data/data.yaml
> +    Какова сложность алгоритма удаления длинных правил грамматики?
кс грамматики?

2024-12-19 15:05 UTC, BaldiSlayer commented on data/data.yaml
> +    Верно ли, что конъюктивные языки являются надмножеством над контекстно-свободными языками?
а это точно галюцинация?

https://gist.github.com/stewkk/809e681a446e36f0fb8484bfc38f05db

https://gist.github.com/stewkk/ebda8ada08e051a255e75b74b80d6685

https://gist.github.com/stewkk/9c056cd738a273b615579b9828bcff9a

2024-12-19 15:11 UTC, BaldiSlayer commented
[дубли](https://github.com/BaldiSlayer/rofl-lab1/pull/157/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1949-R1986)

[такое](https://github.com/BaldiSlayer/rofl-lab1/pull/100/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1740-R1744) уже есть)

2024-12-19 15:17 UTC, AlisaEee commented on data/data.yaml
> +    Верно ли, что конъюктивные языки являются надмножеством над контекстно-свободными языками?
Да, несколько раз переспрашивала в разных формулировках. Она путается

2024-12-19 15:20 UTC, molivka commented
> [дубли](https://github.com/BaldiSlayer/rofl-lab1/pull/157/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1949-R1986) уже есть [такое](https://github.com/BaldiSlayer/rofl-lab1/pull/100/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1740-R1744) )

1. оно не запушено
2. у Алисы расписано + формулировки вопроса прямые

2024-12-19 15:24 UTC, AlisaEee commented
> > [дубли](https://github.com/BaldiSlayer/rofl-lab1/pull/157/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1949-R1986) уже есть [такое](https://github.com/BaldiSlayer/rofl-lab1/pull/100/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1740-R1744) )
> 
> 1. оно не запушено
> 2. у Алисы расписано + формулировки вопроса прямые (и ответы развёрнутые)

Я подумала, что стоит обосновать почему. Она писала какой-то бред. Плюс... Пока проверяла у меня появились сомнения, что модель хорошо приводит примеры языков. Может еще написать примеры регулярных/нерегулярных?

2024-12-19 15:27 UTC, BaldiSlayer commented
> > [дубли](https://github.com/BaldiSlayer/rofl-lab1/pull/157/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1949-R1986) уже есть [такое](https://github.com/BaldiSlayer/rofl-lab1/pull/100/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1740-R1744) )
> 
> 1. оно не запушено
> 2. у Алисы расписано + формулировки вопроса прямые

1. Я уже вмерджил )
2. Про формулировки вопроса ответ простой. [вот](https://github.com/BaldiSlayer/rofl-lab1/pull/138) и все эти вопросы будут к одному ответу ) Видимо нужно закрыть эту таску на этой неделе, чтобы не было вопросов

2024-12-21 10:37 UTC, TonitaN commented on data/data.yaml
> +    Изменится ли язык после удаления из грамматики правил, содержащих недостижимые нетерминалы?
https://gist.github.com/stewkk/4adaeb60fea8c42351051c3cdbc4ecd3

2024-12-21 10:37 UTC, TonitaN commented on data/data.yaml
> +    Изменится ли язык после удаления из грамматики правил, содержащих непорождающие нетерминалы?
https://gist.github.com/stewkk/d8fb981f4d5697b639af67a3eed44f35

Скажите спасибо элементу БЗ с аналогичным вопросом про цепные правила.

2024-12-21 10:37 UTC, TonitaN commented on data/data.yaml
> +    Да, верно. Так как конъюктивные языки - языки, описываемые грамматиками, правила которых имеют вид A -> B1 & ... & B2.
https://gist.github.com/stewkk/6ac4e14b7fbb42c3683d4489e300f4a3

2024-12-21 10:44 UTC, TonitaN requested changes

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Существует ли слово из L, которое является префиксом другого?
А где резолюция? Вопрос @BaldiSlayer действительно указывает на непонятную формулировку, которая ещё и такова, что может ухудшить даже имеющийся т.н. "поиск ближайших"

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Как построить позиционный автомат по грамматике?
Какой грамматике? Нужно упомянуть КС и LR-разбор

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Когда мы только начинаем читать слово, мы находимся перед правой частью S стартового правила S'->.S. Каждый раз при построении блока, мы смотрим на положение разбора слова. В случае, если мы нахо
Пояснить про точку

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    если свертка происходит по финальному S'->S., тогда этот конфликт - конфликт перенос-свертка(с финальным правилом).
Можно этот случай в ответе специально не выделять

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Если свертка происходит в нескольких правилах блока, тогда эта ситуация называется конфликтом свертка-свертка, то есть мы не знаем сколько символов снять со стека, чтобы считать, что мы прошли ра
Или - куда переходить дальше после свертки, если в конфликте есть два правила с одинаковыми правыми частями, но разными нетерминалами в левой части.

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Является ли пересечение контекстно-свободных языков контекстно-свободным языком?
Лучше переформулировать вопрос, т.к. вот:
https://gist.github.com/stewkk/b94704c7538213794d699ef8e48981da

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Приведем конкр-пример: Пусть L1 = {a^n b^n c^i}, где n, i >= 0 и L2 = {a^i b^n c^n}, где n, i >= 0.
*контрпример

2024-12-21 10:44 UTC, TonitaN commented on data/data.yaml
> +    Приведем конкр-пример: Пусть L1 = {a^n b^n c^i}, где n, i >= 0 и L2 = {a^i b^n c^n}, где n, i >= 0.
И тут n>0 строго

2024-12-21 19:16 UTC, BaldiSlayer commented
> > > [дубли](https://github.com/BaldiSlayer/rofl-lab1/pull/157/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1949-R1986) уже есть [такое](https://github.com/BaldiSlayer/rofl-lab1/pull/100/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1740-R1744) )
> > 
> > 
> > 
> > 1. оно не запушено
> > 2. у Алисы расписано + формулировки вопроса прямые
> 
> 1. Я уже вмерджил )
> 2. Про формулировки вопроса ответ простой. [вот](https://github.com/BaldiSlayer/rofl-lab1/pull/138) и все эти вопросы будут к одному ответу ) Видимо нужно закрыть эту таску на этой неделе, чтобы не было вопросов
> 
> UPD: перенос на неопределенный срок

Я доделал!

2024-12-22 16:20 UTC, AlisaEee commented on data/data.yaml
> +    если свертка происходит по финальному S'->S., тогда этот конфликт - конфликт перенос-свертка(с финальным правилом).
Вы имеете ввиду убрать только описание свертки без конфликтов? Или конфликтов тоже?

2024-12-24 15:44 UTC, AlisaEee commented
@TonitaN 
Антонина Николаевна, здравствуйте, посмотрите, пожалуйста, вопросы.

2024-12-24 18:20 UTC, TonitaN reviewed
Расширения нормальные, полезные, только нужно чуть-чуть уточнить

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +    если свертка происходит по финальному S'->S., тогда этот конфликт - конфликт перенос-свертка(с финальным правилом).
Просто убрать всё здесь после аналогично, чтобы не запутывать LLM

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +    если свертка происходит по финальному S'->S., тогда этот конфликт - конфликт перенос-свертка(с финальным правилом).
А здесь как раз можно уточнить, что в конфликте перенос-свертка возникает недетерминизм: продолжать класть символы на стек или снимать их.

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +    Когда язык называется разрешимым?
Уточнить только вопрос: формальный язык, в рамках тьюринг-полной модели вычислимости (да, перестраховка, но нам важно, чтобы не смешались эти вопросы и вопросы про разрешимость проблем для более узких классов задач)

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +    Пусть |Γ| - сумма длин правых частей правил. Данный алгоритм добавляет в грамматику O(|Γ|) новых нетерминалов, O(|Γ|) новых правил длины O(1) и, следовательно, работает за O(|Γ|)
Может, подвязать это к элементу БЗ номер 131?

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +    Все языки, которые могут быть распознаны видимыми стековыми автоматами, также могут быть распознаны детерминированными стековыми автоматами. Однако не все детерминированные контекстно-свободные я
Более того, детерминированными _видимыми_ стековыми автоматами. И в части не все - хорошо бы привести контрпример (он простой очень)

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +  Нет, пересечение LL(k)-языка с регулярным языком не всегда является LL(k)-языком.
Неплохо и здесь контрпример добавить

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +  Правила перехода в автомате Треллиса отображают пару состояний в новое состояние. Правила перехода в автомате Треллиса можно задать через таблицу, где строки и столбцы будут соответсвовать паре сот
*состояний

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +  Правила перехода в автомате Треллиса отображают пару состояний в новое состояние. Правила перехода в автомате Треллиса можно задать через таблицу, где строки и столбцы будут соответсвовать паре сот
Кроме того, неплохо пояснить, что отображаются "соседние" в таблице состояния.

2024-12-24 18:20 UTC, TonitaN commented on data/data.yaml
> +  Таблица по Глайстеру-Шаллиту дает оценку снизу на количество состояний, а таблица по Майхиллу-Нероде - оценку сверху.
*на количество состояний НКА (т.к. таблица по Майхиллу-Нероде - это точная оценка числа состояний в минимальном ДКА)

2024-12-24 18:50 UTC, molivka commented on data/data.yaml
> +  Что такое автомат Треллиса?
дубль с половинкой моего [вопроса](https://github.com/BaldiSlayer/rofl-lab1/pull/154/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R1727) :( 
я, не жадная, но неприятно, что пр'ы (да и issue тоже) никто не чекает

2024-12-24 18:51 UTC, BaldiSlayer commented on data/data.yaml
> +    Когда язык называется разрешимым?
@AlisaEee давай резолвить хотя бы после пуша коммита что ли, а то непонятно, почему вот сейчас это отрезолвлено)

2024-12-24 18:52 UTC, BaldiSlayer commented on data/data.yaml
> +    Когда язык называется разрешимым?
ты можешь коммитов скок хочешь пушить, я все равно их сквошну перед мерджем)

2024-12-24 18:54 UTC, TonitaN commented on data/data.yaml
> +  Что такое автомат Треллиса?
:(
@AlisaEee , надо разобраться (добавить собственный контент и расширить вопрос, чтобы не было дублей).

2024-12-24 18:57 UTC, AlisaEee commented on data/data.yaml
> +  Что такое автомат Треллиса?
Извини, я не заметила

2024-12-26 20:09 UTC, AlisaEee commented
@TonitaN 
Антонина Николаевна, здравствуйте, посмотрите, пожалуйста, правки к вопросам

2024-12-26 22:30 UTC, TonitaN commented on data/data.yaml
> +    Замкнуты ли LL(k)-языки относительно пересечения с регулярным языком?
Кто-то, кажется, брал LL(k)-языки... Нет пересечений?

2024-12-26 22:30 UTC, TonitaN commented on data/data.yaml
> +    Повторные нетерминалы при присвоении атрибутов индексируются по вхождениям в правило слева направо. То есть, если дано правило, что значение атрибута для A увеличивается на единицу от своего стар
Пояснить, что если атрибут предка получает значение от потомка, а не от старого значения)

2024-12-26 22:30 UTC, TonitaN commented on data/data.yaml
> +    Каким образом можно разобрать слово по автомату Треллиса?
@molivka , ок?

2024-12-27 06:29 UTC, molivka commented on data/data.yaml
> +    Каким образом можно разобрать слово по автомату Треллиса?
да, всё ок

2024-12-27 06:34 UTC, molivka commented on data/data.yaml
> +    Замкнуты ли LL(k)-языки относительно пересечения с регулярным языком?
да, Вы правы, Аркадий хотел брать, но я не нашла его pr с вопросами
с вопросами @HumsterProgrammer пересечений нет

2024-12-27 06:52 UTC, HumsterProgrammer commented on data/data.yaml
> +    Замкнуты ли LL(k)-языки относительно пересечения с регулярным языком?
Аркадий, насколько знаю, в процессе. С ним могут быть пересечения, что у меня, что у Алисы

2024-12-27 06:55 UTC, molivka commented on data/data.yaml
> +    Замкнуты ли LL(k)-языки относительно пересечения с регулярным языком?
> Аркадий, насколько знаю, в процессе. С ним могут быть пересечения, что у меня, что у Алисы

тогда он сам должен обеспечить себе «непересечение» :)

2024-12-27 13:34 UTC, AlisaEee commented
@TonitaN 
Антонина Николаевна, здравствуйте, я поправила вопросы и преобразовала к нужному виду, но вопрос со сложностью пока не добавила. Вы уверены что номер 131? Там про ХНФ .

2024-12-27 13:38 UTC, BaldiSlayer commented
> @TonitaN Антонина Николаевна, здравствуйте, я поправила вопросы и преобразовала к нужному виду, но вопрос со сложностью пока не добавила. Вы уверены что номер 131? Там про ХНФ .

Пришлось выйти с больничного на пару минут :clown_face:. Так там как раз про приведение к НФХ). И одна из стадий приведения к НФХ - удаление длинных правил. Поэтому да, к 131)

2024-12-27 15:14 UTC, AlisaEee commented
Ну это понятно, по разве там к месту упоминание сложности? Но конечно, добавлю

2024-12-27 17:22 UTC, BaldiSlayer commented
У тебя конфликты не решены, мне ещё птичка нашептала, что у тебя 3к дифф, надо померджиться на master)

2024-12-28 12:27 UTC, BaldiSlayer approved these changes

2024-12-28 12:27 UTC, merged