Лабораторная работа 5. Теньшов Дмитрий
BaldiSlayer/rofl-lab1 pull request #159
Opened 2024-12-20 13:30 UTC by Hexxet

2024-12-20 15:12 UTC, TonitaN requested changes
Везде в вопросах, где нет про ДКА, и не чистая алгебра, нужно добавить сокращение ДКА. 
И нет собственно базового определения, см:
https://gist.github.com/stewkk/a2ae41c8bbdfda7479ae037a5e482380

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    где n = |Q|,так, чтобы действие букв из Σ сохраняло этот циклический порядок.
Пример нужен

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    Задача #SHORT-SW, то есть задача перечисления синхронизирующих слов детерминированного конечного автомата (ДКА) A длины l
Тут наименование задачи SHORT-SW не нужно, пишите целиком.

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    Чему равна оценка порога синхронизации синхронизируемого n-автомата с нулём?
Что значит с нулём и что такое порог синхронизации?

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    Когда говорят, что подстановка постоянной длины удволетворяет условию совпадения?
*удовлетворяет

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +  answer: >
*автоматов (и лучше подписать в скобочках "ДКА")

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    Порог избегаемости (обозначается at(A))  - это максимума длин кратчайших слов, избегающих состояния
Не надо вводить обозначение, которое потом нигде не используется. Можно и словами.

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    если ∀w ∈ Σ^* p. w ≠ q. w. Если ДКА A не является синхронизируемым, то он должен иметь взаимные блокировки.
Пояснить словами, что такое взаимная блокировка

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    как перестановка множества состояний, либо фиксирует все состояния, кроме одного.
Фиксирует - это что? Действует на них как единица или наоборот, отображает в единственное состояние?

2024-12-20 15:12 UTC, TonitaN commented on data/data.yaml
> +    ДКА A = Q, Σ, δ⟩ с алфавитом Σ = {a_1, . . . , a_l} определяет подстановку постоянной длины l на множестве Q
очень не удачно выбран индекс l - он похож на 1. Лучше другой.

2024-12-21 20:59 UTC, BaldiSlayer commented
@TonitaN, если что - у нас немного поменялась логика. Мы к одному ответу делаем несколько вопросов теперь. id генерится скриптом, он при дампе сортирует поля в алфавитном порядке. Так что сначала стоит answer, а потом questions

2024-12-21 21:01 UTC, BaldiSlayer commented
https://github.com/BaldiSlayer/rofl-lab1/pull/138
Все же смог допинать на этой неделе + в рамках этой таски затащил ещё одну маленькую активность по улучшению UX (теперь сообщение апдейтится, а не новое отправляется по готовности ответа от LLM)

2024-12-24 18:36 UTC, TonitaN requested changes
У вас много где ДКА A = ⟨Q, Σ⟩, хотя ДКА не только множеством состояний и алфавитом задаются. Нужно эту конструкцию переформулировать: ДКА А с множеством состояний Q над алфавитом Σ

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +    S'' для любых s ∈ S'' и x ∈ X. Если S'' устойчиво в A, то,  ограничивая функцию
Добавить перевод с алгебраического на человеческий, это же не сложно

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +  - 'Что такое подавтомат?
*подавтомат (конечного или бесконечного автомата) - т.к. определено и для автоматов с бесконечным числом состояний

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +    ∈ S)(∀x ∈ X)((s, t) ∈ θ ⇒ (δ(s, x), δ(t, x)) ∈ θ). Каждая конгруэнция θ автомата
Тоже добавить одну строчку расшифровки

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +    для любых s ∈ S, x ∈ X.
Пример конгруэнции (а лучше два - тот, что был в курсе и какой-нибудь тривиальный) ведь можно привести?

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +  - 'Что такое фактор-автомат?
Тоже развернуть: в контексте конечной или бесконечной системы переходов

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +    z, что z.a = z для каждой буквы a ∈ Σ. Будем называть такие состояния нулевыми,
Ну и разобрать два случая таких нулевых состояний.

2024-12-24 18:36 UTC, TonitaN commented on data/data.yaml
> +    есть для любого слова из Σ^*, если ДКА начинается в состоянии p, то он никогда
Не совсем по-русски. Лучше так: ни одно слово не переводит ДКА из состояний p и q в одно и то же состояние.

2025-01-01 12:18 UTC, TonitaN approved these changes
Аппрув, т.к. правки уже косметические, можно внести их без ревью

2025-01-01 12:18 UTC, TonitaN commented on data/data.yaml
> +    которого все переходы ведут в себя; нулевое состояние, которое не имеет переходов.
Ну по факту да, если автоматы сокращённые. Иначе говоря, либо принимающее все слова по их префиксу (такое, класс эквивалентности в моноиде которого совместен со всеми словами), либо ловушка.

2025-01-01 12:18 UTC, TonitaN commented on data/data.yaml
> +    состояний, либо фиксирует все состояния (то есть если буква фиксирует состояние
Ведь фиксирует состояние - действует как единица на этом состоянии, а не на всех состояниях, кроме этого. А у вас написано, как будто как раз его и не фиксирует.
То есть нужно исправить смешение определения фиксации и применения этого термина в конкретном случае.

2025-01-01 21:03 UTC, BaldiSlayer approved these changes
нет, нельзя

2025-01-01 21:04 UTC, merged