Лабораторная работа 5. Пишикина Мария
BaldiSlayer/rofl-lab1 pull request #160
Opened 2024-12-20 14:30 UTC by m-tisssh

2024-12-21 11:10 UTC, TonitaN requested changes

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    Верно ли, что синхронизируемость автомата означает в точности наличие в определённом моноиде матрицы, в которой один столбец состоит из единиц, а все
Как этот моноид связан с автоматом?

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    Полиномиальным алгоритмом для аппроксимации порога синхронизации назовем произвольный алгоритм U, который для каждого синхронизируемого автомата A за
Что такое порог синхронизации, уточнили? Я не проверяла по всем вопросам сразу.

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    2-подмножество R_i , что R_i * P_j для всех j < i.
Что здесь *? Она очень сильно перегружена уже как операция.

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +  answer: >
Что значит фиксироваться буквой? Нужно уточнить

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    Максимальный префиксный код синхронизирован тогда и только тогда, когда синхронизируем его декодер. При этом слова, синхронизирующие код X, – это в
Пояснить про декодер - что это за автомат

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    Максимальный префиксный код X над Σ называют синхронизированным, если существует такое слово z ∈ Σ^+, что для любого y ∈ Σ^* слово yz можно разложить
Нужно напомнить про максимальный префиксный код тут же

2024-12-21 11:10 UTC, TonitaN commented on data/data.yaml
> +    За какое время в наихудшем случае выполняется алгоритм Берлинкова (Berlinkov’s algorithm) для проверки синхронизируемости?
Синхронизируемости ДКА (добавить в вопрос)
И пояснить, откуда берутся тесты

2024-12-21 21:15 UTC, m-tisssh commented on data/data.yaml
> +    За какое время в наихудшем случае выполняется алгоритм Берлинкова (Berlinkov’s algorithm) для проверки синхронизируемости?
Заменила этот вопрос, так как алгоритм Берлинкова достаточно объёмный

2024-12-24 18:05 UTC, TonitaN reviewed
Аккуратно уточнить вопросы, расшаривающие общие термины с другими областями теории автоматов.

2024-12-24 18:05 UTC, TonitaN commented on data/data.yaml
> +    \ R_i не принадлежит P_j для всех j < i. \n"
Всё-таки следует ещё пояснить, как это связано с синхронизируемостью

2024-12-24 18:05 UTC, TonitaN commented on data/data.yaml
> +  - 'Что такое циклический детерминированный конечный автомат?
Тут я немного опасаюсь, что это смешается с циклами в графе автомата :(
Лучше немного расширить вопрос, подчеркнув алгебраический контекст (трансмоноид).

2024-12-24 18:05 UTC, TonitaN commented on data/data.yaml
> +  - 'Что такое детерминированный конечный автомат (ДКА) с 2-пересечениями?
Та же тема - уточнить, что в контексте трансмоноидов

2025-01-02 08:56 UTC, TonitaN approved these changes

2025-01-04 03:01 UTC, merged