Лабораторная работа 5. Кочетков Денис
BaldiSlayer/rofl-lab1 pull request #169
Opened 2024-12-26 19:32 UTC by HumsterProgrammer

2024-12-26 22:47 UTC, TonitaN requested changes
Краткость - сестра таланта)

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'LR(0)
лучше расширить на "LR(0) контекстно-свободные языки", иначе могут появиться автоматы Лебедева)

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +- answer: 'LR(0) языки - языки, для которых возможно построить позиционный автомат не содержащий конфликтов.
здесь тоже уточнить - что кс-языки. И расширить, что это в точности детерминированные кс-языки, обладающие беспрефиксностью.

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'LR(n)
аналогично LR(0) расширить вопрос и ответ

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    LR(n) разбором возможно разобрать любой детерминированный КС язык.
Повторить, что при n>=1

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты LL(k) языки?
Всё точно согласовано с другими по темам? Просто вижу уже у второго человека LL(k)-замкнутость, и возможно, это не конец

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    LL(k) языки не замкнуты относительно операций пересечения, дополнения, морфизмов и разворота слова.
ответ - на другой вопрос: относительно чего не замкнуты

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Если язык LL(k) является ли он LL(n), n>k?
*КС язык. И предлагаю не экономить и написать "если n больше k"

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +- answer: 'Линейные конъюнктивные языки - языки заданные линейной конъюнктивной грамматикой.
Расшифровать линейность

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты VPL?
(лучше в скобочках тоже расшифровку)

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Методы определения является ли КС-язык детерминированным
Это конкретно методы доказательства того, что язык детерминированный. Тут нет ничего про опровержение. Нужно уточнить вопрос.

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    2. Анализ дополнения - Если дополнение детерминировано, то и сам язык детерминированный
тут добавить - дополнение КС-языка, чтобы не смешивалось с прочими

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    3. Построение Детерминированного PDA, разбирающий язык.
расшифровать сокращение + *разбирающего

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    T -> aTb | aT | ε
Кратко пояснить, почему так

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +- answer: 'Да, может. Можно привести два языка палиндромов в алфавитах {a,b} и {b,c}.
четных палиндромов

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +    VPL языки являются подклассом Линейных языков.
линейных конъюнктивных языков

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +- answer: 'Линейные языки - подкласс контекстно-свободных языков и линейных конъюнктивных языков, порождаемый линейными грамматиками.
VPL языки не являются подклассом линейных КС языков. Сможете сами построить контрпример: VPL язык, но не линейный?

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Линейные языки
контекстно-свободные или конъюнктивные?

2024-12-26 22:47 UTC, TonitaN commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты линейные языки?
есть ли смысл объединить два очень похожих вопроса с очень похожими ответами? Кмк да.

2024-12-27 17:13 UTC, HumsterProgrammer commented on data/data.yaml
> +- answer: 'Линейные языки - подкласс контекстно-свободных языков и линейных конъюнктивных языков, порождаемый линейными грамматиками.
Понял. ПСП - VPL, но не линейный язык. Прошу прощения за помешательство

2024-12-27 17:17 UTC, HumsterProgrammer commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты линейные языки?
вы имеете ввиду вопросы замкнутость линейных и замкнутость линейных конъюнктивных языков?

2024-12-27 17:22 UTC, HumsterProgrammer commented on data/data.yaml
> +  - 'Если язык LL(k) является ли он LL(n), n>k?
Бот ответил нормально
https://gist.github.com/stewkk/c2fc897c91758b0f434c8cc6a7b14750
Но
https://gist.github.com/stewkk/34be196b099c25343355506ec513af86

2024-12-27 18:19 UTC, TonitaN commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты линейные языки?
Да. Мне кажется, можно сделать один элемент БЗ сразу с двумя вопросами к нему.

2024-12-31 14:48 UTC, HumsterProgrammer commented on data/data.yaml
> +  - 'Относительно каких операций замкнуты LL(k) языки?
Убрал из своих вопросов. Изменю чуть позже

2024-12-31 16:45 UTC, TonitaN commented on data/data.yaml
> +- answer: 'LR(0) контекстно-свободные языки - языки, для которых возможно построить позиционный автомат не содержащий конфликтов.
Тут "детерминированные беспрефиксные", а в следующем как раз не надо. Сбила вас с толку, соотнося ответ с вопросом, находящимся выше его.

2024-12-31 16:45 UTC, TonitaN commented on data/data.yaml
> +    LR(n), n>0 разбором возможно разобрать любой детерминированный беспрефиксный КС язык.
тут беспрефиксность уже не нужна

2024-12-31 16:45 UTC, TonitaN commented on data/data.yaml
> +- answer: 'Да, может. Можно привести два языка четных палиндромов в алфавитах {a,b} и {b,c}.
Повторить для глупенькой LLM и студентов, что языки палиндромов в алфавите хотя бы из 2 символов не детерминированы.

2025-01-02 16:26 UTC, BaldiSlayer commented on data/data.yaml
> +  - 'Грамматика префиксов Правильных скобочных последовательностей'
```suggestion
  - 'Грамматика префиксов правильных скобочных последовательностей'
```

)

2025-01-02 16:27 UTC, BaldiSlayer commented on data/data.yaml
> +#https://gist.github.com/stewkk/6c3c08ad1fdffd7e81c9985339c736c8
а это случайно не удалится при выполнении скрипта `id_gen`?

я бы лучше подкинул это к описанию pr)

2025-01-02 16:28 UTC, HumsterProgrammer commented on data/data.yaml
> +#https://gist.github.com/stewkk/6c3c08ad1fdffd7e81c9985339c736c8
да думаю не страшно. Если понадобится, легко найду

2025-01-03 12:58 UTC, HumsterProgrammer commented
@TonitaN исправил вопросы по правкам. Готов к ревью

2025-01-03 20:11 UTC, TonitaN approved these changes
Я сделаю аппрув, т.к. большинство правок - косметика. Но есть одна серьёзная, с отрицанием леммы о накачке для LR-языков. Там нужно поправить очень аккуратно.

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +    В свою очередь, Линейные контекстно-свободные языки замкнуты относительно операций объединения и пересечения с регулярными языками, объединения с линейными языками, морфизмов и обратных морфизмов
Продолжая линию партии Алексея, здесь Линейные -> линейные

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +    Линейные конъюнктивные языки могут описать любой VPL язык, но не любой КС и конъюнктивный языки, так как необходимо выполнение свойств линейности.
в скобках - (visibly pushdown), чтобы LLM было легче соотносить аббревиатуру с данными

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +    Пересечения, объединения, конкатенации(При условии, что разбиения алфавитов на внутренние, вызывающие и возвращающие символы одинаковые), замыкания Клини, взятия дополнения, морфизмов, обратных м
Про (как минимум) морфизмы нужно опять повторить эту же мантру про разбиение алфавита.
Т.к. вне этого контекста конечно нет, см. пример {a^n c b^n | n>0} после h(a)=h(b)=a, h(c)=c.

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +        2. не существует разбиения x = x_1 x_2 x_3, y = y_1 y_2 y_3, z = z_1 z_2 z_3, такое что
такого что накачки (см.ниже) всегда (для всех i) принадлежат языку. Отрицание уже сделано выше (в "не существует")

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +        Если выполнено одно из условий
если выполнены оба условия. Т.к. в исходной лемме как раз выполнялось одно из (существует либо накачка префикса, либо синхронная накачка) - то в её отрицании должно выполняться, что нет обоих. Собственно, вы всегда её именно так и применяли)

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +  - 'Лемма о сжатии
лемма о сжатии для линейных конъюнктивных грамматик (иначе llm может попутать её с другими леммами для кс-языков)

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +    существует константа k >= 0, и любое слово из языка w, |w| > k, то существует разбиение
*такая что любое слово w языка достаточной длины (|w|>k) может быть представлено как w=xyz, при этом...

2025-01-03 20:11 UTC, TonitaN commented on data/data.yaml
> +  - 'Методы определения является ли КС-язык детерминированным
Ещё лемма Шаллита есть у @BaldiSlayer .

2025-01-04 05:03 UTC, TonitaN commented
@BaldiSlayer , рано влили. Денису ещё нужно было кое-что исправить.

2025-01-04 05:26 UTC, HumsterProgrammer commented
> @BaldiSlayer , рано влили. Денису ещё нужно было кое-что исправить. 

В main не влили еще. @BaldiSlayer перенес правки из main в мою ветку

2025-01-04 07:46 UTC, HumsterProgrammer commented on data/data.yaml
> +        Если выполнено одно из условий
> Собственно, вы всегда её именно так и применяли)

Это... многое объясняет. Аватарка более чем передает осознание мое...

2025-01-04 13:45 UTC, BaldiSlayer approved these changes

2025-01-04 13:46 UTC, merged