Лабораторная работа 5. Дьячков Егор
BaldiSlayer/rofl-lab1 pull request #175
Opened 2024-12-29 11:30 UTC by Egorrrad

2025-01-01 17:28 UTC, Egorrrad commented
@TonitaN, добрый вечер! Сделал вопросы для бз. Можете пожалуйста посмотреть их

2025-01-02 09:00 UTC, TonitaN requested changes

2025-01-02 09:39 UTC, TonitaN requested changes
У вас пересечения с @GekK9 , так что пока они не разрешатся, смотреть не буду.
У Никиты приоритет - он уже давно сделал PR с вопросами.

2025-01-02 11:30 UTC, Egorrrad commented on data/data.yaml
> +⇾* — переписывание за произвольное число шагов, начиная с 0.
убрал

2025-01-08 13:49 UTC, Egorrrad commented
@TonitaN, добрый вечер! Добавил два дополнительных вопроса. Пересечения удалил

2025-01-08 15:10 UTC, HumsterProgrammer commented on data/data.yaml
> +существуют, однако для типичных конструкций языков программирования их вполне можно избежать.
LR грамматики(если я правильно понял, подразумевается LR(k)) описывают в точности детерминированные КС языки.
Возможно стоит это добавить в ответ

2025-01-08 15:53 UTC, BaldiSlayer commented on data/data.yaml
> +    Напиши лемму о накачке для DCFL (Deterministic context free language)
это один вопрос, нам нужно два разных, погугли что такое массивы в `yaml`

2025-01-08 15:57 UTC, BaldiSlayer commented on data/data.yaml
> +    Напиши лемму о накачке для DCFL (Deterministic context free language)
[тут](https://github.com/BaldiSlayer/rofl-lab1/pull/175/files#diff-035c0723fdb49646da8dd735de972edcd2c66dc801913a836323964da8b1c327R4432-R4434) было норм

2025-01-08 16:19 UTC, Egorrrad commented on data/data.yaml
> +    Напиши лемму о накачке для DCFL (Deterministic context free language)
исправил

2025-01-08 17:29 UTC, Egorrrad commented on data/data.yaml
> +    Напиши теорему Грейбах
заменил на просто теорему Грейбах

2025-01-08 17:31 UTC, Egorrrad commented on data/data.yaml
> +    - 'Дай определение двух-уровневой грамматики
теперь в вопросе тоже слитно

2025-01-14 23:39 UTC, TonitaN approved these changes
Аппрув относительный, т.к. почти всё ок, но есть небольшие опечатки.

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    - 'Теорема Грейбах'
Теорема Грейбах о неразрешимости свойств в семействах формальных языков

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    Двухуровневая грамматика - это тройка <G1,G2, z>, в которой:
А что такое z здесь? Пояснить словами.

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    а) перемещение приведения: если находящийся в вершине стека символ k помечает приводящее состояние автомата,
Обычно это называют действием свертки

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    б) перемещение сдвига: если находящийся в вершине стека символ к помечает неприводящее состояние автомата,
Обычно это называется действием переноса

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    - 'Какие действия возможны в любой момент времени при выполнении LR-процесса?'
Не в любой, это лучше опустить

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    Доказательство. Нужно доказать, что никакие две различных строки u, v не могут по- пасть в один класс.
лишний перенос

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +    меньше состояний, чем типичный анализатор, основанный на LK(1)-пунктах. Путем аккуратного добавления предпросмотров
Что-то пошли опечатки. 
Кроме того, есть ещё собственно simple LR - (SLR) - вот это вообще почти чистый LR(0)+разрешение конфликтов по множествам Follow

2025-01-14 23:39 UTC, TonitaN commented on data/data.yaml
> +      где r - регулярное выражение?'
просто - языку регулярного выражения

2025-01-15 01:00 UTC, Egorrrad commented
исправил опечатки

2025-01-15 08:55 UTC, HumsterProgrammer approved these changes
Единственное, в чем не совсем уверен - излишнее использование символов unicode, там где они могли бы и не использоваться(например, красивая Сигма, вместо просто Сигмы). Не знаю как нейросеть будет реагировать.
В остальном вроде все нормально

2025-01-15 10:34 UTC, HumsterProgrammer commented on data/data.yaml
> +    но не допускает такую декомпозицию при i < k переходов, скажем, что 𝒜 задаёт КС-язык с k-недетерминированностью.
может тут тоже заменить букву A?

2025-01-15 10:40 UTC, HumsterProgrammer approved these changes

2025-01-15 10:44 UTC, merged