Parser: add lexer and base for parser
BaldiSlayer/rofl-lab1 pull request #2
Opened 2024-09-24 07:28 UTC by HumsterProgrammer

2024-09-24 07:57 UTC, BaldiSlayer reviewed
Из основного:
1) Переименовать проект, чтобы не надо было это делать потом, так как парсер у нас также будет веб сервером
2) перестать паниковать ;D, а именно отказаться от паник в сторону ошибок.
3) поставить пробелы, это нужно сделать много где, кажется `go fmt путь/к/файлу.go` поможет

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +type Lexem struct{
после `struct` лучше поставить пробел

сделай `go fmt путь/к/файлу.go`

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +package main;
точка с запятой в конце не нужна и надо назвать `package` по-другому

давай сам проект назовем `parser` (так будет называться папка в корне репозитория)

создадим там папку `internal`, в ней папку `lexer` и туда положим этот файл (только назовем его `lexer.go`)

Соответственно функцию `lexer` надо сделать публичной (aka назвать ее `Lexer`)

парсер будем писать в `parser/internal/parseer/parser.go`

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +func lexer(a string) (res []Lexem){
кажется что тут не сильно нужен именованный параметр, т.е. давай возвращать просто `[]Lexem`

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +	variables := "variables"
давай вынесем это в блок констант, раз это не будет меняться

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +		switch a[i]{
я бы попробовал сделать это с помощью `map`, но тут наверное дело вкуса, так что можешь оставить и так

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +	i := 0;
а зачем создаем переменную вне цикла? го будет `for i :=0; i < len(a); i++ {`

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +					panic("unknown symbol at pos " + strconv.Itoa(i) + ":"+string(a[i]))
Давай возвращать ошибку вместо паники? То есть функция будет возвращать `([]Lexem, error)`, а ты напишешь тут `return nil, fmt.Errorf("unknown symbol at pos %d:%c", i, a[i])`

от паники нужно будет делать рекавери, а это будет грустно, старайся везде возвращать `error` с помощью `fmt.Errorf` или `errors.New()`

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +				if a[i] == '\n' || a[i] == '\r'{
пооставляй пожалуйста комментов, я если честно вообще не понимаю, что тут происходит

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +				if a[i] == '\n' || a[i] == '\r'{
Вообще было бы круто эту часть вынести в отдельную функцию, возвращать из нее тоже `[]Lexem, error`, и делать в духе
```go
lexems, err := эта_функция(и тут тоже че-то)
if err != nil {
  return nil, err
}

res = append(res, lexems...)
```

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +		panic("on index"+ strconv.Itoa(l.index)+ " expected "+ strconv.Itoa(Ltype)+ ", found " + strconv.Itoa(l.lex_type))
выше писал про возврат ошибок

еще не очень понял зачем тебе две функции, которые делают одно и то же, кроме паники

2024-09-24 07:57 UTC, BaldiSlayer commented on parse/parseTRS.go
> +func main(){
в `Go` есть если что встроенные тесты, можешь погуглить почитать, мне кажется это будет удобнее)

2024-09-24 08:00 UTC, BaldiSlayer commented on parse/parseTRS.go
> +package main;
@stewkk

2024-09-24 08:02 UTC, BaldiSlayer commented on parse/parseTRS.go
> +func main(){
если лень, можешь перезолвить и не переписывать)

2024-09-24 08:02 UTC, BaldiSlayer commented on parse/parseTRS.go
> +func main(){
но имхо это удобнее

2024-09-24 08:06 UTC, stewkk commented on parse/parseTRS.go
> +func lexer(a string) (res []Lexem){
> кажется что тут не сильно нужен именованный параметр, т.е. давай возвращать просто `[]Lexem`

задушил =))

2024-09-24 08:06 UTC, stewkk commented on parse/parseTRS.go
> +	variables := "variables"
> давай вынесем это в блок констант, раз это не будет меняться

тоже задушил =)))

2024-09-24 08:11 UTC, stewkk commented on parse/parseTRS.go
> +					panic("unknown symbol at pos " + strconv.Itoa(i) + ":"+string(a[i]))
Вот тут кстати вопрос, как обрабатывать такие ошибки. Нам надо для LLM возвращать текстовое описание, и, кажется, это лучше делать на русском. Поэтому, видимо, надо делать кастомный класс ошибок с возможностью получить сообщение об ошибке на русском

2024-09-24 08:13 UTC, stewkk commented on parse/parseTRS.go
> +package main;
> @stewkk

принесу ПР с файловой структурой, которую я предлагаю

2024-09-24 08:20 UTC, BaldiSlayer commented on parse/parseTRS.go
> +	i := 0;
кстати говоря это вообще неверно, строка у тебя это слайс байт, так что если нам дадут на вход какой-то не оч хороший символ, то мы будем итерироваться неверно

давай заюзаем

```go
runes := []rune(a)
for i, value := range a {
}
```

2024-09-24 08:20 UTC, BaldiSlayer commented on parse/parseTRS.go
> +	i := 0;
@HumsterProgrammer, обновил

2024-09-24 08:21 UTC, BaldiSlayer commented on parse/parseTRS.go
> +func lexer(a string) (res []Lexem){
и го назовем переменную не `a`, иначе непонятно, что она в себе несет

2024-09-24 08:47 UTC, HumsterProgrammer commented on parse/parseTRS.go
> +	i := 0;
> кстати говоря это вообще неверно, строка у тебя это слайс байт, так что если нам дадут на вход какой-то не оч хороший символ, то мы будем итерироваться неверно
> 
> давай заюзаем
> 
> ```go
> runes := []rune(a)
> for i, value := range a {
> }
> ```

Здесь я не совсем знаю как корректно обработать слово variables. Если это как в питоне(то есть даже если я внутри цикла прибавлю что-то к i, то на следующей итерации он все равно будет i+1).
По этому по индексам пробегаюсь. 

rune сделаю

2024-09-24 08:48 UTC, HumsterProgrammer commented on parse/parseTRS.go
> +				if a[i] == '\n' || a[i] == '\r'{
> Вообще было бы круто эту часть вынести в отдельную функцию, возвращать из нее тоже `[]Lexem, error`, и делать в духе
> ```go
> lexems, err := эта_функция(и тут тоже че-то)
> if err != nil {
>   return nil, err
> }
> 
> res = append(res, lexems...)
> ```

Часть с проверкой лексем?

2024-09-24 10:06 UTC, BaldiSlayer commented on parse/parseTRS.go
> +				if a[i] == '\n' || a[i] == '\r'{
наверное, я если честно не оч понимаю, что происходит в том коде

2024-09-24 21:32 UTC, BaldiSlayer commented on parse/parseTRS.go
> +		switch a[i]{
Вообще говоря с точки зрения производительности лучше даже не `map`, а `slice` с `silent` actions

Можно будет подумать над этим, когда будет готова обычная реализация

2024-09-24 21:32 UTC, BaldiSlayer reviewed
Добавка

2024-09-25 08:09 UTC, BaldiSlayer commented on parser/parseTRS.go
> +	lex_variables := []rune("variables")
В гошке надо писать `lexVariables`

2024-09-25 08:48 UTC, BaldiSlayer commented on parser/parseTRS.go
> +func TRS_parseVars(/*input string,*/ m []Lexem, index *int) {
Ты кодогенерацией пользуешься? Или поч у тебя все начинается с `TRS_`

Мне кажется лучше было бы создать
```go
type Parser struct {

} 

```

И на него накрутить все нужные методы

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +			if runes[i] == '\n' || runes[i] == '\r' { // если перевод строки(причем могут быть 2), добавить лексему перевод строки
можем вынести это в отдельную функцию?

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +					t := true
еслии честно, название переменной ни о чем не говорит

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +				return nil, fmt.Errorf("unknown symbol at pos %d:%c", i, runes[i])
душню:

возможно `pos` лишнее
```go
fmt.Errorf("unknown symbol at %d:%c", i, runes[I])
```

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +func (p Parser) parseVars(/*input string,*/ m []Lexem, index *int) {
если `input` не нужен, мб сразу уберем?

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +	*index++
тут подушню, фиксить не обязательно

вообще, кажется удобнее не по указателю переменную передавать, а возвращать из функции количество, на которое следует сдвинуть

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +func (p Parser) parseVars(/*input string,*/ m []Lexem, index *int) {
сразу же еще подушню, а почему не возвращается `error`? Или у нас не может быть ошибок в `parseVars`? я не шарю

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +func (p Parser)Lexer() ([]Lexem, error) {
тут после `(p Parser)` пробел

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +			} else if runes[i] >= 'a' && runes[i] <= 'z' || runes[i] >= 'A' && runes[i] <= 'Z' { // если встретилась буква
`unicode.IsLetter` не подойдет?

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +	text string
а поч не хотим хранить индекс, на котором мы сейчас остановились в парсинге вот тут?
Тогда делаем ресивер указателем и все, не надо будет везде его передавать, так как все методы у нас будут реализованы на `Parser`

и, да, подушны
```go
pe Parser struct {
```
пробельчик )

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +func (p Parser) parseRules(m []Lexem, index *int)     {
а поч тут табы до `{`?

2024-09-29 10:26 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +	lexCheck(m[*index], lexEQ)
а почему не обрабатываем ничего, что из нее пришло? Ни ошибку, ни `true/false`

По идее кстати нам не нужно возвращать `true/false`, потому что мы можем понять ок все или нет с помощью
```go
if err != nil {
// все равно что false
}
// тут true
```

2024-09-29 10:43 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +				if runes[i] == 'v' && i+8 < len(runes) { // проверяем на "variables"
А что такое 8? В слове `variables` 9 букв

2024-09-29 10:47 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +					j := 0
Почему это не в `for`?

2024-09-29 10:53 UTC, stewkk requested changes

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	//"errors"
nitpick: удалить бы

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	text string
~Давай я gofmt закоммичу~ а не, это Денису пуллить придется, ну такое

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	text string
Вообще надо линтер сделать @BaldiSlayer

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	text string
А про индекс поддерживаю

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	runes := []rune(p.text)
не знал, что так можно, лайк

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +			} else if runes[i] >= 'a' && runes[i] <= 'z' || runes[i] >= 'A' && runes[i] <= 'Z' { // если встретилась буква
Ну оно же русские буквы пропустит, например :/

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS_test.go
> +	"./parseTRS"
./parseTRS лишнее тут, не? Т.е. без этого импорта все будет работать

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +		lexCheck(m[*index], lexEOL)
Ты тут везде не проверяешь, что возвращает `lexCheck`. Т.е. проверка ничего не делает

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	*index++
Не понял тут идею с количеством, на которое следует сдвинуть

2024-09-29 10:53 UTC, stewkk commented on pkg/parser/parseTRS.go
> +	*index++
Лучше как ты говорил вынести index в структурку
и сделать `func (p *Parser)...`

2024-09-29 11:02 UTC, stewkk commented on pkg/parser/parseTRS.go
> +			} else if runes[i] >= 'a' && runes[i] <= 'z' || runes[i] >= 'A' && runes[i] <= 'Z' { // если встретилась буква
Оно пропустит русские буквы тоже

2024-09-29 11:04 UTC, stewkk commented on pkg/parser/parseTRS.go
> +				if i < len(runes)-1 && (runes[i] == '\n' && runes[i+1] == '\r' || runes[i] == '\r' && runes[i+1] == '\n') {
Я бы вынес условие из этого if в отдельную фукнцию. Ну и можно подумать, как это упростить. Мб можно конвертировать в строку и сделать switch, например

2024-09-29 11:05 UTC, stewkk commented on pkg/parser/parseTRS.go
> +				if runes[i] == 'v' && i+8 < len(runes) { // проверяем на "variables"
@BaldiSlayer написал бы тест, на котором оно делает out of bounds access =)

2024-09-29 11:06 UTC, stewkk commented on pkg/parser/parseTRS.go
> +					j := 0
Да тут же можно строки сравнивать, не?

2024-09-29 11:07 UTC, stewkk commented on pkg/parser/parseTRS.go
> +					j := 0
Типа `string(runes[i:9]) == "variables"` (наверное так работает)

2024-09-29 11:10 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +	*index++
Ну идея с колвом на которое следует сдвинуть это

```go
func h(m []Lexem) int {
}

offset := h(l)
index += offset
```

но я потом подумал, что было бы круче засунуть `index` в структурку, да)

2024-09-29 11:12 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +			} else if runes[i] >= 'a' && runes[i] <= 'z' || runes[i] >= 'A' && runes[i] <= 'Z' { // если встретилась буква
окей, давай тогда сделаем свою функцию, которая будет проверять является ли это буквой, чтобы не городить длинный `if`

2024-09-29 11:14 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +				if runes[i] == 'v' && i+8 < len(runes) { // проверяем на "variables"
ахах, потом мне на Галуа правда покажут, что я дурик, а так - норм тема

и, да, число 9 хардкодить тоже не надо, кажется мы хотели вынести `variables = "variables"` в константу, почему не можем сделать тупо `len(variables)`?

2024-09-29 11:17 UTC, BaldiSlayer commented on pkg/parser/parseTRS.go
> +					j := 0
не, это будет паника, так как ты срезом можешь выйти за границы слайса

давай сделаем как я выше написал
```
 число 9 хардкодить тоже не надо, кажется мы хотели вынести variables = "variables" в константу, почему не можем сделать тупо len(variables)?
```

2024-09-29 11:33 UTC, stewkk commented on pkg/parser/parseTRS.go
> +				if runes[i] == 'v' && i+8 < len(runes) { // проверяем на "variables"
> ахах, потом мне на Галуа правда покажут, что я дурик, а так - норм тема
> 
> и, да, число 9 хардкодить тоже не надо, кажется мы хотели вынести `variables = "variables"` в константу, почему не можем сделать тупо `len(variables)`?

умно

2024-09-29 11:34 UTC, stewkk commented on pkg/parser/parseTRS.go
> +					j := 0
> не, это будет паника, так как ты срезом можешь выйти за границы слайса

так ты сначала проверишь длину, а затем возьмешь слайс

2024-09-30 15:17 UTC, stewkk commented on parser/trsrules/parseTRS.go
> +	return true
А это ок? =)

2024-09-30 15:17 UTC, stewkk commented on parser/trsrules/parseTRS.go
> +		p.parseArgs()
тут пропускаешь ошибку

2024-09-30 15:18 UTC, stewkk commented on parser/trsrules/parseTRS.go
> +		p.parseTermsTail()
Тут ошибки не проверяешь, мб добавить?

2024-09-30 15:18 UTC, stewkk commented on parser/trsrules/parseTRS.go
> +		p.parseTerm()
и тут

2024-09-30 21:12 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS_test.go
> +	p := Parser{text: peano}
nitpick: тут лучше для разделения поставить enter

2024-09-30 21:13 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS_test.go
> +	p := Parser{text: peano}
аналогично чуть ниже
вообще говоря линтеры будут на это ругаться, надо разбивать это на блоки вида

```go
err := p.Lexer()
if err != nil{
	t.Error(err)
}

err = p.parseTRS()
if err != nil{
	t.Error(err)
}
```

2024-09-30 21:14 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS_test.go
> +	if err != nil {
и тут лучше заюзать кстати `require.NoError` из "github.com/stretchr/testify/require"

2024-09-30 21:14 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +	if err != nil {
nitpick: можно сразу написать `return err`

2024-09-30 21:15 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +		if err != nil{
nitpick: а ты `gofmt` делаешь?

2024-09-30 21:19 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +					for ; j < 9; j++ {
а тут 9 это тоже длина `varialbes`?

2024-09-30 21:20 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +					t := true
давай сделаем `t` -> `isWordVariablesFinded`, хз, я же верно понял, что тут происходит?

2024-09-30 21:22 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +				return fmt.Errorf("unknown symbol at pos %d:%c", i, runes[i])
@stewkk а у нас на русском ошибки или на английском?

2024-09-30 21:22 UTC, BaldiSlayer commented on internal/parser/trsrules/parseTRS.go
> +			} else if runes[i] >= '0' && runes[i] <= '9' {
nitpick: мб вынесем `runes[i] >= '0' && runes[i] <= '9'` в функцию `isDigit()`?

2024-10-01 07:13 UTC, stewkk commented on internal/parser/trsrules/parseTRS.go
> +				return fmt.Errorf("unknown symbol at pos %d:%c", i, runes[i])
у меня на русском, но это не крит

2024-10-01 07:15 UTC, stewkk commented on internal/parser/trsrules/parseTRS.go
> +			if runes[i] == '\n' || runes[i] == '\r' { // если перевод строки(причем могут быть 2), добавить лексему перевод строки
Предлагаю забить

2024-10-01 19:42 UTC, merged