Филимонов Михаил
BaldiSlayer/rofl-lab1 pull request #62
Opened 2024-10-28 08:21 UTC by advanced12iq

2024-10-28 08:52 UTC, TonitaN requested changes
Почти хорошо, остались небольшие замечания.

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    а возможные результаты применения — натуральные числа.
Добавить, что рекурсивные функции вычисляют те же классы алгоритмов, что и машины Тьюринга (а то именно по формулировке тезиса это не очень понятно)

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    в нашем перечислении, то M' определяет, допускает ли M_i вход w_i. Поскольку M допускает L_u, то она
Вы поймёте, что такое w_i и L_d, не заглядывая в соседние вопросы? Надо, чтобы было понятно.

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    Является ли язык Le, состоящий из кодов всех МТ, языки которых пусты, рекурсивно-перечислимым/рекурсивным?
У вас везде подчёркивания отделяли тип языка от L. Лучше добавить.

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    допускающей Lu. 4. Если M_i допускает w, то и M допускает свой вход, т.е. M_i. Понятие M_i, “i-й машины
Lu => L_u , и расшифровать

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    Почему универсальный язык L_u является рекурсивно-перечислимым, но не рекурсивным.
Добавить в ответ, что такое универсальный язык

2024-10-28 08:52 UTC, TonitaN commented on data/data.yaml
> +    Посредством сведения ПСП к вопросу о неразрешимости КС-грамматики можно доказать неразрешимость многих вопросов
не к вопросу о неразрешимости, а к вопросу об определении некоторых свойств КС-грамматики - так будет более правильно по смыслу.

2024-10-30 17:00 UTC, advanced12iq commented
@TonitaN, проверьте, пожалуйста.

2024-10-30 17:04 UTC, BaldiSlayer commented on data/data.yaml
> +    Разрешим ли вопрос о неоднозначности КС-грамматики
может тут на всякий случай расшифруем, что такое КС-грамматика? И ниже ПСП я бы на всякий тоже расшифровал бы как "правильная скобочная последовательность"

2024-10-30 17:05 UTC, BaldiSlayer commented on data/data.yaml
> +    списков A и B, дает одну и ту же цепочку, т.е. w_i_1 w_i_2 …w_i_m = x_i_1 xi_2 …x_i_m. В таком случае последовательность
кажется потерял запятые: `w_i_1, w_i_2, …, w_i_m = x_i_1, xi_2, …, x_i_m`

2024-10-30 17:07 UTC, BaldiSlayer commented on data/data.yaml
> +    Le – пустой язык состоит из кодов всех МТ, языки которых пусты. Он не рекурсивно-перечислим.
тут пропустили `_`, должно быть `L_e`

2024-10-30 17:16 UTC, advanced12iq commented on data/data.yaml
> +    списков A и B, дает одну и ту же цепочку, т.е. w_i_1 w_i_2 …w_i_m = x_i_1 xi_2 …x_i_m. В таком случае последовательность
Это цепочки, пишутся без запятых

2024-10-30 17:22 UTC, BaldiSlayer commented on data/data.yaml
> +    Понятие M_i, “i-й машины Тьюринга”. Это МТ M, кодом которой является i-я двоичная цепочка w_i.
nitpick: `МТ М` если честно выглядит не очень, может напишем машина Тьюринга?

2024-10-30 17:25 UTC, BaldiSlayer commented on data/data.yaml
> +    ему не удовлетворяет), либо содержит все РП-языки. В противном случае свойство назы
тут возможно стоит расшифровать, что такое РП-языки, потому что в этом вопросе не было расшифровано

2024-10-30 17:35 UTC, advanced12iq commented on data/data.yaml
> +    Понятие M_i, “i-й машины Тьюринга”. Это МТ M, кодом которой является i-я двоичная цепочка w_i.
Это общепринятая аббревиатура, которая расшифрована в каждом месте где встречается (а она в сочетании с M встречается минимум в половине вопросов), поэтому если проблема только в эстетичности я не буду менять.

2024-10-30 22:20 UTC, TonitaN commented
Ок.

2024-10-31 18:29 UTC, closed without merging