Шиятов Наиль
BaldiSlayer/rofl-lab1 pull request #63
Opened 2024-10-28 13:03 UTC by NailorSH

2024-10-28 13:53 UTC, NailorSH commented
@TonitaN, проверьте, пожалуйста

2024-10-29 09:14 UTC, TonitaN requested changes
Сначала убиваем теховские теги, потом продолжаю ревью уже по содержанию.

2024-10-29 09:14 UTC, TonitaN commented on data/data.yaml
> +    Как реализуется алгоритм MemDFA для проверки принадлежности слова w к языку L в ДКА?
Техническое обозначение перенести только в ответ и согласовать (member vs memDFA)

2024-10-29 09:14 UTC, TonitaN commented on data/data.yaml
> +    Реализация операции дополнения для ДКА проста. Поскольку ДКА имеет единственный прогон для каждого слова, который принимается, если автомат достигает заключительного состояния, можно просто помен
В основном у всех юникод. Не надо латех, тем более такие вещи как \textbf - вообще кринж.
Переделать всё далее согласно этому замечанию.

2024-11-02 17:07 UTC, BaldiSlayer commented on data/data.yaml
> +    Какая сложность проверки равенства языков двух ДКА с использованием алгоритма Хопкрофта для вычисления CSR?
> алгоритма Хопкрофта для вычисления CSR

давай напишем тут, что такое `CSR`

ну и можно расшифровать ДКА наверное)

2024-11-02 17:18 UTC, BaldiSlayer commented on data/data.yaml
> +    Обозначив head(aw) = a и tail(aw) = w для a ∈ Σ и w ∈ Σ*, алгоритм выглядит следующим образом: MemDFA[A](w, q) Вход: ДКА A = (Q, Σ, δ, q0, F), состояние q ∈ Q, слово w ∈ Σ* Выход: Возвращает true
если честно - прочитав это с первой итерации я вообще ничего не понял

может это какое-то общепринятое значение, но я не знаю что такое `MemDFA[A](w, q)`, для меня это выглядит как generic, где тип подставляется под A. 

Может все же как-то поподробнее напишем? 

Например не
> Вход: ДКА A = (Q, Σ, δ, q0, F), состояние q ∈ Q, слово w ∈ Σ*

а

> На вход подается ДКА (детерминированный конечный автомат) A (Q, Σ, δ, q0, F, на самом деле не знаю насколько важно описывать как именно задается ДКА, кажется нельзя его задать как-то по-другому), состояние q ∈ Q, слово w ∈ Σ*


Тоже самое с "на выход", что такое `1.` и `2.`, для меня осталось загадкой..

2024-11-02 17:21 UTC, BaldiSlayer commented on data/data.yaml
> +    Реализация операции дополнения для ДКА проста. Поскольку ДКА имеет единственный прогон для каждого слова, который принимается, если автомат достигает заключительного состояния, можно просто помен
nitpick: я бы если честно сделал "заключительные" -> "финальные" состояния, так как-то привычно.

2024-11-02 17:25 UTC, BaldiSlayer commented on data/data.yaml
> +    Реализация операции дополнения для ДКА проста. Поскольку ДКА имеет единственный прогон для каждого слова, который принимается, если автомат достигает заключительного состояния, можно просто помен
еще если честно хотелось бы поменять `единственный прогон для каждого слова`, звучит как-то не очень, я вот сходу не понял, что за прогон

я бы заменил это на
> слово распознается единственным способом

так как он детерминированный и мы в каждом состоянии для слова знаем куда пойдем)

2024-11-02 17:28 UTC, BaldiSlayer commented on data/data.yaml
> +    Какая сложность проверки равенства языков двух ДКА с использованием алгоритма Хопкрофта для вычисления CSR?
coarsest stable refinement - вроде вот это оно

2024-11-02 21:55 UTC, BaldiSlayer commented on data/data.yaml
> +    Реализация операции дополнения для ДКА проста. Поскольку ДКА имеет единственный прогон для каждого слова, который принимается, если автомат достигает заключительного состояния, можно просто помен
тех я не пробовал даже читать.. но хотелось бы, чтобы там были не тупо
Ввод: куча буков
Вывод: еще куча букв

а что-то более вменяемое и читаемое

2024-11-02 22:02 UTC, BaldiSlayer commented on data/data.yaml
> +    Операция дополнения для ДКА сохраняет минимальность, потому что каждое состояние дополненного автомата $Comp(A)$ распознаёт дополнение языка, которое распознавало то же состояние в исходном автом
у нас есть поинт, чтобы не назвать новый автомат вместо `$Comp(A)$` тупо `B`?

> Согласно следствию, ДКА минимален, если его состояния распознают различные языки.

Какому следствию?

2024-11-02 22:11 UTC, BaldiSlayer commented on data/data.yaml
> +    Как алгоритм проверяет, что язык, распознаваемый одним ДКА, является подмножеством языка, распознаваемого другим ДКА?
кажется, что в такой формулировке имеется в виду какой-то конкретный алгоритм, это так?

2024-11-02 22:14 UTC, BaldiSlayer commented on data/data.yaml
> +    Алгоритм проверяет, что язык $L(A_1)$, распознаваемый ДКА $A_1$, является подмножеством языка $L(A_2)$, распознаваемого ДКА $A_2$, с помощью построения параллельного автомата $[A_1, A_2]$. Для ка
а что такое параллельный автомат?
Если честно - очень похоже на тупо произведение автоматов

2024-11-02 22:18 UTC, BaldiSlayer commented on data/data.yaml
> +    Равенство языков двух ДКА $L(A_1) = L(A_2)$ проверяется с помощью симметрической разности $L(A_1) \\Delta L(A_2)$. Если симметрическая разность пуста, то языки равны. Алгоритм $EqDFA$ модифицируе
я почему-то совсем не уверен, что `EqDFA` и `InclDFA` это "общепринятые" названия алгоритмов (можешь поправить, если я ошибаюсь)

> для состояний $[q_1, q_2]$ 

наверное нужно уточнить, что q1 бралось из первого ДКА, а q2 из второго

2024-11-02 22:20 UTC, BaldiSlayer commented on data/data.yaml
> +    Какие два важных преимущества имеет алгоритм EqDFA по сравнению с минимизацией автоматов?
опять же - я не уверен, что это название общепринятое и используется повсеместно, а не только в этой книжке, в любом случае нужно пояснить что делает этот алгоритм кмк

2024-11-02 22:22 UTC, BaldiSlayer commented on data/data.yaml
> +    Какие два важных преимущества имеет алгоритм EqDFA по сравнению с минимизацией автоматов?
еще наверное есть смысл говорить про то, при каком использовании этих алгоритмов вообще получается преимущество? Мне неочевидно, какую задачу мы сейчас решаем (сори за душноту)

2024-11-02 22:23 UTC, BaldiSlayer commented on data/data.yaml
> +    Первое преимущество заключается в том, что алгоритм $EqDFA$ работает \"на лету\" (on-the-fly), позволяя тестировать равенство языков, пока строятся автоматы $A_1$ и $A_2$, и останавливать работу
тут бы раскрыть что за автоматы $A_1$ и $A_2$

> чтобы он возвращал свидетельство (witness)
имхо по-русски лучше будет назвать контрпример

2024-11-09 22:26 UTC, TonitaN requested changes
It's a trap!
Без контекстов про состояния-ловушки получим очень много очень неочевидных для неспециалиста галлюцинаций. И остальное нужно дополнить.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Обозначив head(aw) = a и tail(aw) = w для a ∈ Σ и w ∈ Σ*, алгоритм выглядит следующим образом: MemDFA[A](w, q) Вход: ДКА A = (Q, Σ, δ, q0, F), состояние q ∈ Q, слово w ∈ Σ* Выход: Возвращает true
Поддерживаю, нужно больше поясняющих слов.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    1. Q′ ← Q; δ′ ← δ; q′₀ ← q₀; F′ ← ∅
Что такое L(B) и L(A)? Пояснить всё словами.
Плюс начисто забыли про состояние-ловушку, а ведь это максимально важный момент!

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Операция дополнения для ДКА сохраняет минимальность, потому что каждое состояние дополненного автомата Comp(A) распознаёт дополнение языка, которое распознавало то же состояние в исходном автомат
1. Следствию чего?
2. И опять уточнить про ловушку: если минимальный ДКА был сокращённым (trim), то чтобы дополненный имел то же число состояний, из него возможно придётся убирать состояние-ловушку, если оно там появилось.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    1. Q′ ← Q; δ′ ← δ; q′₀ ← q₀; F′ ← ∅
Про trap state текущая модель даже не считает нужным упомянуть, вопрос очень важен для корректности БЗ:
https://gist.github.com/stewkk/58f25212c31ddf159e6126b15cd519d8

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +          - q₀₁ ← δ₁(q₁, a); q₀₂ ← δ₂(q₂, a)
Ну вот видно же, что для объединения это будет работать тогда и только тогда, когда в ДКА все ловушки явно присутствуют. Поправить.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +          - добавить ([q₁, q₂], a, [q₀₁, q₀₂]) в δ
И вообще развернуть пространное рассуждение про разные бинарные операции, и логику алгоритма при работе с каждой.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Выходной детерминированный конечный автомат (ДКА) от алгоритма BinOp будет иметь O(|Q₁| ⋅ |Q₂|) состояний, независимо от выполняемой булевой операции. Для демонстрации достижимости этого предела
Не нужно давать алгоритмам такие бесконтекстные имена. Нужно сослаться на его название словами.
И здесь интересно будет разобрать случай числа состояний у автомата для объединения двух автоматов, распознающих взаимно простые.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    ДКА принимает пустой язык тогда и только тогда, когда у него нет заключительных состояний. Алгоритм Empty(A) возвращает true, если множество заключительных состояний F пусто, и false в противном
Не алгоритм, а функция, т.к. алгоритм вот как раз зависит от деталей представления.
(вовсе не обязательно там должна быть булева переменная, стандартно автомат представляют как кортеж множеств, и там это тупо проверка на непустоту F, но при условии, что все состояния достижимы, а об этом здесь ни слова)

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Как алгоритм проверяет, что язык, распознаваемый одним ДКА, является подмножеством языка, распознаваемого другим ДКА?
+1

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Алгоритм проверяет, что язык L(A₁), распознаваемый ДКА A₁, является подмножеством языка L(A₂), распознаваемого ДКА A₂, с помощью построения параллельного автомата [A₁, A₂]. Для каждого состояния
Параллельного, или же автомата для произведения?
Параллельный может рассматривать переходы по разным буквам из первого и второго элемента кортежа.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    ДКА принимает универсальный язык Σ* тогда и только тогда, когда все его состояния являются заключительными. Алгоритм UnivDFA(A) возвращает true, если множество заключительных состояний F совпадае
И что такое нормальная форма?

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Равенство языков двух ДКА L(A₁) = L(A₂) проверяется с помощью симметрической разности L(A₁) Δ L(A₂). Если симметрическая разность пуста, то языки равны. Алгоритм EqDFA модифицирует алгоритм InclD
Опять сослаться на алгоритмы словами

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Какая сложность проверки равенства языков двух ДКА с использованием алгоритма Хопкрофта для вычисления CSR?
Бисимуляция, ага.

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Если используется алгоритм Хопкрофта для вычисления CSR, то проверка равенства языков может быть выполнена за время O(n log n), где n — это сумма состояний автоматов A₁ и A₂.
Да и вообще заменить CSR на бисимуляцию, это одно и то же для ДКА

2024-11-09 22:26 UTC, TonitaN commented on data/data.yaml
> +    Какие два важных преимущества имеет алгоритм EqDFA по сравнению с минимизацией автоматов?
Согласна, преимущество по сравнению с каким алгоритмом? Вопрос хороший, и ответ можно написать очень содержательный, например, сказав о возможности построения контрпримеров для облегчения тестирования равенства языков автоматов.

2024-11-11 11:43 UTC, closed without merging

2024-11-11 12:00 UTC, stewkk commented
Упс, извините. Подчищал ветки, а этот PR был в ветку data-it-2, которая больше не нужна

2024-11-11 12:00 UTC, stewkk commented
Переоткрою

2024-11-11 12:01 UTC, stewkk commented
Надо переоткрыть в правильную ветку (main)

2024-11-11 12:46 UTC, NailorSH commented
Окей, сейчас переоткрою