Еделькин Герман
BaldiSlayer/rofl-lab1 pull request #66
Opened 2024-10-31 14:06 UTC by HermanDp45

@TonitaN
Добрый день, Антонина Николаевна, поправил свои вопросы с учетом комментариев.

Общее количество вопросов уменьшилось на 1 в силу того, что он, в действительности, оказался перефразированной теоремой Клини (изначально сделано было это, конечно, не специально, просто в учебнике была такая интерпретация, которую не распознал по неопытности)

По вашему наставлению, договорились с остальными ребятами по поводу оформления, поэтому:
1. Отделил индексы посредством "_"
2. Всякие символы по юникоду только теперь
3. Подчистил ссылки (на рисунки, на иные теоремы и т.д)
4. Постарался почистить кальку
5. Добавил по необходимости в ответы расшифровки некоторых вещей

2024-10-31 15:53 UTC, BaldiSlayer commented on data/data.yaml
> +    В хорошо написанном регулярном выражении должны быть сбалансированы какие факторы?
![image](https://github.com/user-attachments/assets/03d4ffd5-dd31-4236-aa4f-8883faae1c3f)

мб лучше 

> какие факторы должны быть сбалансированны в хорошо написанном регулярном выражении

?)

2024-11-02 15:49 UTC, BaldiSlayer commented on data/data.yaml
> +  Преобразование НКА в ДКА может занимать экспоненциальное время относительно количества состояний НКА. Вычисление ε-замыкания для n состояний занимает O(n³), так как нужно исследовать до n² дуг. Это
> Это можно сделать с помощью алгоритма Уоршалла.

Мб подкинем инфу, что это за алгоритм? Вообще я вангую, что это [он](https://neerc.ifmo.ru/wiki/index.php?title=Алгоритм_Флойда), обычно его Флойдом называют, но не суть. Давай напишем "алгоритма Флойда-Уоршелла нахождения кратчайших путей между всеми парами вершин"

2024-11-02 15:57 UTC, BaldiSlayer commented on data/data.yaml
> +  Теорема (Майхилл-Нероуд) для регулярных языков
а почему _Майхилл-Нероуд_ в скобках? Вряд ли есть просто теорема для регулярных языков, либо я чего-то не знаю, если это так - можешь просто отрезолвить

2024-11-03 11:27 UTC, TonitaN requested changes
Мне в целом понравилась эта итерация, но есть несколько тонких моментов, одна почти галлюцинация (когда в ответе об НКА имелись в виду расширенные НКА с поддержкой нерегулярных операций, но это нигде не говорилось) и один откровенный дубль.

2024-11-03 11:27 UTC, TonitaN commented on data/data.yaml
> +  Теорема (Майхилл-Нероуд) для регулярных языков
Лучше теорема Майхилла-Нероде (Нероуде).
Я знаю, откуда такое могло быть: в пакете maththm часто используют окружение Теорема, и в опциональном аргументе можно дать её название. В статьях все привыкли к этому, и это уже в рамках традиции. Но не в латехе так делать не надо.

2024-11-03 11:27 UTC, TonitaN commented on data/data.yaml
> +  Теорема Майхилла–Нероуда. Пусть L —язык, и пусть ≡_L — отношение эквивалентности на множестве строк, где u ≡_L u', если для всякой строки v строки uv и u'v или обе лежат в L или обе не лежат. Утвер
Добавьте ещё термин "суффиксная конгруэнтность" для контекста. И можно сказать, что существуют аналоги теоремы Майхилла-Нероуда для других классов языков.

2024-11-03 11:27 UTC, TonitaN commented on data/data.yaml
> +  Как задается Бинарное отношение ≈_L на множестве Σ*?
Это отношение выше обозначалось по-другому. Унифицировать, и добавить термин суффиксная конгруэнтность.

2024-11-03 11:27 UTC, TonitaN commented on data/data.yaml
> +  Лемма о разрастании для регулярных языков
Это дубль леммы о накачки в вашем же ответе, и будет засчитываться как дубль. Скажите в ответе, что лемма о разрастании также называется леммой о накачке (по-английски - никаких разночтений: pumping lemma).

2024-11-10 19:56 UTC, HermanDp45 commented on data/data.yaml
> +  Лемма о разрастании для регулярных языков
Я это видел, но там был упор на доказательство, поэтому все же решил оставить так, как оно есть (дополнительно подумал, что, возможно, будет неплохо иметь второй вариант названия, т.к мне он встречался тоже достаточно в сети)
Но поправил так, как Вы порекомендовали.
Остальное тоже)

2024-11-10 20:00 UTC, HermanDp45 commented on data/data.yaml
> +  answer: >
Я конечно, поправил, но что-то успел много раз запутаться в процессе, изначально я все же ошибся в самом вопросе, когда его переносил, поэтому оставил два варианта, учитывая то, что один из них будет считаться дубликатом, конечно.

2024-11-11 16:03 UTC, TonitaN requested changes
Кроме мелких правок, есть сомнения в одном дополнении + нужно расшифровать сокращения и перегруженные операторы

2024-11-11 16:03 UTC, TonitaN commented on data/data.yaml
> +    • Теорема Кнута-Грасса-Майера: Это теорема, которая является аналогом теоремы Майхилла-Нерода для контекстно-свободных языков.
Это очень похоже на галлюцинацию. Кнут 100% не занимался алгебраическими свойствами КС-языков, это делали Вайс, Уелхер, и некоторые другие, и теоремы там дюже сложные. Теперь вот не знаю и про теорему о разделении (больше похоже на лемму о накачке для DCFL). Если нет достоверных материалов, лучше убрать и написать про суффиксную конгруэнтность древесных языков, и конечное  число классов суффиксной конгруэнтности в сбалансированных словах для Visibly Pushdown Languages. Если есть уверенность в том, что пишете - сослаться на источники (реальные ссылки) и кратко привести формулировки.

2024-11-11 16:03 UTC, TonitaN commented on data/data.yaml
> +  Как задается Бинарное отношение ≡_L на множестве Σ*?
Словами назвать это отношение. И повторить название в ответе.

2024-11-17 17:51 UTC, molivka commented on data/data.yaml
> +    Три закона для коммутативности и ассоциативности регулярных выражений
пересекается по смыслу с вопросом @seregazakharin «Какие операторы регулярных выражений ассоциативны? Коммутативны? Дистрибутивны? Идемпотентны?», но подробнее расписан и с примерами

2024-11-17 18:08 UTC, molivka commented on data/data.yaml
> +  Проще говоря, слова x и y находятся в отношении ≡_L, если для каждого слова z добавление его к x приводит к слову, принадлежащему языку L, тогда и только тогда, когда добавление того же слова z к y
может вместо «добавление» взять слово «приписывание» и уточнить с какой стороны? (да, по формуле видно, но это на случай, если откажемся от формул в итоге)

2024-11-17 18:11 UTC, molivka commented on data/data.yaml
> +    Какие факторы должны быть сбалансированны в хорошо написанном регулярном выражении?
дубль самого себя, первый вопрос

2024-11-20 09:25 UTC, HermanDp45 commented on data/data.yaml
> +  Проще говоря, слова x и y находятся в отношении ≡_L, если для каждого слова z добавление его к x приводит к слову, принадлежащему языку L, тогда и только тогда, когда добавление того же слова z к y
Поменял, но надеюсь формулы останутся в итоге)

2024-11-20 09:27 UTC, HermanDp45 commented on data/data.yaml
> +    Какие факторы должны быть сбалансированны в хорошо написанном регулярном выражении?
Прошу обратить внимание на самый первый комментарий в этом обсуждении (вместе со всей его веткой ответов)

2024-11-20 09:32 UTC, HermanDp45 commented
@TonitaN, добрый день! Добавил исправления.

2024-11-22 21:08 UTC, molivka commented on data/data.yaml
> +  Что называется конфигурацией ДКА M = (Q, Σ, s, F, 𝛿)
кстати, вопрос: зачем тут спец символы?
ведь мы на том же рк / экзе не будем вбивать их...

2024-11-23 20:59 UTC, TonitaN commented on data/data.yaml
> +  Что называется конфигурацией ДКА M = (Q, Σ, s, F, 𝛿)
В вопросе не надо, правильно.

2024-11-23 21:00 UTC, TonitaN commented
Убираем спецсимволы из вопросов и можно принимать.

2024-11-24 12:20 UTC, HermanDp45 commented
@TonitaN, @BaldiSlayer, @molivka. Добрый день, заключительные правки были внесены \_(*^*)_/

2024-11-24 12:36 UTC, BaldiSlayer commented
@HermanDp45, прив. Реши конфликты плз))

2024-11-24 13:21 UTC, HermanDp45 commented
> @HermanDp45, прив. Реши конфликты плз))

Папа сам порешал конфликты  😘

2024-11-24 13:22 UTC, BaldiSlayer commented
мерджу)

2024-11-24 13:27 UTC, BaldiSlayer commented on data/data.yaml
> +    Три закона для коммутативности и ассоциативности регулярных выражений
пока оставим, но потом надо будет посмотреть делает ли это лучше поиск близких)

2024-11-24 13:28 UTC, BaldiSlayer approved these changes

2024-11-24 13:29 UTC, merged