13 questions Egorova
BaldiSlayer/rofl-lab1 pull request #70
Opened 2024-11-04 18:36 UTC by AlisaEee

2024-11-04 18:39 UTC, BaldiSlayer commented on data/data.yaml
> +    Учитыват ли трансформационный моноид финальность состояний?
учитывает

2024-11-04 18:42 UTC, BaldiSlayer commented on data/data.yaml
> +    Какие свойства есть у множества функций переходов ДКА?
го напишем здесь ДКА (детерминированного конечного автомата)

2024-11-04 18:44 UTC, BaldiSlayer commented
общий комментарий:
разделяй каждую тройку (вопрос, ответ, автор) переносом строки

если не поняла - посмотри, как это делали выше)

2024-11-04 19:03 UTC, BaldiSlayer commented on data/data.yaml
> +    Состояния q_i и q_j в НКА А бисимирлярны (q_i ~ по A  q_j), если они связаны LTS-бисимуляцией и имеют одинаковую финальность в А.
а почему тут речь именно про НКА? Ловушки могут быть и в ДКА, финальные тоже.. 
биссимилярность разве только на НКА определена?

и напиши пж словами что такое `одинаковая финальность`

2024-11-04 19:06 UTC, AlisaEee commented on data/data.yaml
> +    Трансформационный моноид M_A для ДКА А - это моноид функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда q_i -> q_j по a в А, где q_i и q_j - состояния.
Зачем? Только в одном месте нет смысла

2024-11-04 19:31 UTC, BaldiSlayer commented on data/data.yaml
> +    1. Если пустое слово принадлежит L(r_1), то частичная производная от r_1 r_2 по c получается путем взятия частичных производных от r_1 и r_2 по c и конкатенацией результата со вторым регулярным в
скинул only for fun, не считать за то, на что надо исправить

2024-11-08 17:15 UTC, AlisaEee commented
@TonitaN
Добрый вечер, Антонина Николаевна. Я поправила свои вопросы с учетом комментариев.

2024-11-08 20:24 UTC, TonitaN requested changes
Финальная чистка

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Полученные частичные производные используются для построения автомата Антимирова, где состояния соответствуют этим частичным производным.
Пояснить, что алгоритм построения производных возвращает их множество, а состояния автомата соответствуют элементам этого множества.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Состояния q_i и q_j в НКА А бисимирлярны (q_i ~ по A q_j), если они связаны LTS-бисимуляцией и имеют одинаковую финальность в А.
Уже аугментируем данные опечатками) Сила.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Чтобы определить отношение бисимуляции на конечных автоматах, к отношению бисимуляции на LTS(labelled transition system - тройка {S,∑,Q}, где S,∑,Q - множества состояний, меток и переходов соотве
А лучше было бы не тройку писать, а по-русски: система размеченных переходов.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Состояния q_i и q_j в НКА А бисимирлярны (q_i ~ по A  q_j), если они связаны LTS-бисимуляцией и имеют одинаковую финальность в А, то есть состояния либо оба являются конечными, либо оба не являют
Мне кажется, тут вообще не нужно обозначение для отношения бисимуляции, хватит слов.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Состояния q_i и q_j в НКА А бисимирлярны (q_i ~ по A  q_j), если они связаны LTS-бисимуляцией и имеют одинаковую финальность в А, то есть состояния либо оба являются конечными, либо оба не являют
А вот что такое LTS-бисимуляция, одним предложением пояснить.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Трансформационный моноид M_A для ДКА А - это моноид функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда q_i -> q_j по a в А, где q_i и q_j - состояния.
Ну это же очень сложно, стрелочку на фразу "переходит в" изменить, и добавить слова "состояние" перед q_i, q_j )

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Трансформационный моноид M_A для ДКА А - это моноид функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда q_i -> q_j по a в А, где q_i и q_j - состояния.
И уточнить, что моноид над базисом функций, там есть и их композиции же.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    3) Трансмоноид строится для ДКА без ловушек; переход в ловушку обозначается в таблице переходов прочерком.
Пояснить, что это за таблица вообще.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Определяем соответсвие между буквами и множествами переходов по ним и будем расширять этот список новыми словами в лексикографическом порядке. Если очередное слово задает такую же трансформацию,
Вот тут про таблицу тоже уместно вспомнить

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    w_i ~ по L w_j \n ⇔ для любых x, y (x*w_i*y ∈ L ⇔ x*w_j*y ∈ L).
Звездочки здесь для конкатенации очень плохо - у нас они зарезервированы под итерации. В свободных моноидах обычно просто пробел используется.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Синтаксический моноид - атрибут языка, а трансформационный моноид - атрибут конкретного языка.
Конкретного автомата, распознающего этот язык...

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Синтаксический моноид M(L) - это множество его классов эквивалентности относительно ~ по L (отношение бисимуляции по L). То есть такая полугруппа с единицей над w ∈ ∑*, что  w_i = w_j ⇔ w_i ~ по
Множество чьих классов эквивалентности?

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    О чем говорит теорема Майхилла-Нероуда?
Во избежание диких переводов, в скобочках приводим английскую транслитерацию фамилий.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    L-некоторый регулярный язык. Определим отношение эквивалентности по Нероуду как: w_i ≡ по L w_j ⇔ для любых y (w_i*y ∈ L ⇔ w_j*y ∈ L).
Опять звёздочки

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    L-некоторый регулярный язык. Определим отношение эквивалентности по Нероуду как: w_i ≡ по L w_j ⇔ для любых y (w_i*y ∈ L ⇔ w_j*y ∈ L).
И пояснить формулу словами.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    =>: Пусть L регулярен. Тогда он порождается некоторым DFA A с конечным числом состояний N. Значит, множество {q_i | q_0 ➝ по w q_i} конечно, а для каждых двух w_1, w_2 таких, что q_0 ➝ по w_1 q_i
Может, тут тоже лучше "переходит по ... в ...", а не стрелку.

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    3) Если w_i*a ≡ по L w_j, то  w_i ➝ по a w_j.
Звёздочка

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    3) Пометим все множества {q_i, q_j} такие, что существует такой a, что (q_i ➝ по a  q_1' и q_j ➝ по a q_2' и {q_1',q_2'} - помеченная пара).
Тут тоже лучше "переходит в"

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    Для доказательства минимальности автомата необходимо построить таблицу классов эквивалентности. Для построения таблицы выбираются w_i - префиксы, которые приводят в различные состояния автомата.
Подчеркнуть, что только для детерминированных и конечных.

Для доказательства минимальности автомата первым способом таблиц необходимо....

2024-11-08 20:24 UTC, TonitaN commented on data/data.yaml
> +    При доказательстве минимальности DFA достаточно подобрать [log_2(n)]+1 различающих суффиксов z_i, где n - число состояний автомата.
Добавить, что есть второй способ - минимизировать автомат и показать, что результат равен исходному с точностью до нумерации состояний.

2024-11-15 14:05 UTC, BaldiSlayer commented on data/data.yaml
> +    Трансформационный моноид M_A для ДКА А - это моноид функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда q_i -> q_j по a в А, где q_i и q_j - состояния.
```suggestion
    Трансформационный моноид M_A для ДКА А - это моноид функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда есть переход из состояния q_i в состояние q_j по символу a в А.
```

и добавь про базис функций

2024-11-17 18:19 UTC, molivka commented on data/data.yaml
> +    Какие условия необходимы для бисимуляции двух НКА?
просто как fun fact (если потом будем связывать вопросы)
вопрос связан с @NailorSH «Какой альтернативный подход существует для проверки равенства двух детерминированных конечных автоматов...»

2024-11-17 18:22 UTC, molivka commented on data/data.yaml
> +    О чем говорит теорема Майхилла-Нероуда(англ. Myhill-Nerode theorem)?
дубль с @HermanDp45 «Теорема Майхилла-Нероде (Нероуде) для регулярных языков»

2024-11-20 06:12 UTC, AlisaEee commented
@TonitaN
Доброе утро, Антонина Николаевна. Посмотрите, пожалуйста, вопросы.

2024-11-23 21:09 UTC, TonitaN approved these changes
В принципе можно принять, но местами не повредит немного улучшить язык.

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** Частичные производные Антимирова — это метод, который используется в классической теории автоматов для преобразования регулярных выражений в конечные автоматы. Для вычисления частичной про
Лучше "алгоритм вычисляет частичные производные рекурсивно"

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** Трансформационный моноид M_A для ДКА А - это моноид над базисом функций F_a таких, что F_a(q_i) = q_j тогда и только тогда, когда состояние q_i переходит в состояние q_j по a в А.  Иначе м
Расшифровать, что строки являются действиями над состояниями автомата

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** Для трансформационного моноида M_A верны эти свойства: 1) M_A определяется фактормножеством классов эквивалентности и правилами переписывания, задающими эквивалентность. Пустое слово обычн
Расшифровать F_{w_i} - множество возможных действий над состояниями автомата

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** Определим отношение синтаксической конгруэнтности слов:  w_i ~ по L w_j ⇔ для любых x, y (x w_i y ∈ L ⇔ x w_j y ∈ L).  То есть если мы можем вставить слово w_i в любое место в слове из язы
Можно проще: заменяя подслова из одного класса эквивалентности друг на друга, мы не меняем принадлежности слова, в котором сделана замена, языку.

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** L-некоторый регулярный язык. Определим отношение эквивалентности по Нероуду как: w_i ≡ по L w_j ⇔ для любых y (w_i y ∈ L ⇔ w_j y ∈ L). Таким образом, два слова эквивалентны по Нероуду тогд
Тут тоже можно сказать проще: замена префикса слова на другой префикс из того же класса эквивалентности не меняет принадлежности слова языку.

2024-11-23 21:09 UTC, TonitaN commented on data/output.md
> +**Ответ:** Минимизация ДКА. Рассмотрим один из методов минимизиции:  1) Построим таблицу всех двухэлементных множеств {q_i, q_j} q_i, q_j ∈ Q (множество состояний). 2) Пометим все множества {q_i, q_j
Почему бы в п.2 просто не сказать "пометим все пары, один элемент которых финальный, а другой нет". И так же проще сказать в 3.

2024-11-24 12:35 UTC, BaldiSlayer approved these changes

2024-11-24 12:36 UTC, BaldiSlayer commented
конфликты порешал, между

2024-11-24 12:36 UTC, merged