feat: new deploy
BaldiSlayer/rofl-lab1 pull request #78
Opened 2024-11-09 19:45 UTC by BaldiSlayer

2024-11-10 10:28 UTC, stewkk commented on .github/workflows/images.yaml
> +          git push
А это ок, что после коммита с апдейтом, sha будет уже другой?

2024-11-10 10:28 UTC, stewkk commented on LLM/utils/patch.py
Да это просто надо патчем сделать

2024-11-10 10:28 UTC, stewkk commented on dockerfiles/llm.dockerfile
> +COPY /LLM/utils/patch.py /usr/local/lib/python3.12/site-packages/googletrans/client.py
Лайк

2024-11-10 10:29 UTC, stewkk commented on LLM/utils/patch.py
Имел в виду patch.py сделать googletrans.patch, и применять в dockerfile

2024-11-12 23:21 UTC, BaldiSlayer commented on .github/workflows/images.yaml
> +          git push
ну, оно как минимум работает =)
и это ок, оно на этом коммите не билдит образы

2024-11-12 23:22 UTC, BaldiSlayer commented
@stewkk ревью плз)

2024-11-14 08:40 UTC, stewkk requested changes

2024-11-14 08:40 UTC, stewkk commented on .github/workflows/images.yaml
> +    branches: [ "main", "impl-tgbot", "new-deploy" ]
Давай вот это уберем?

```suggestion
    branches: [ "main" ]
```

2024-11-14 08:40 UTC, stewkk commented on docker-compose.yml
>        - ./patch.py:/usr/local/lib/python3.12/site-packages/googletrans/client.py
Давай уберем сразу патч

2024-11-14 08:40 UTC, stewkk commented on LLM/app/config/config.py
> +        self.index = faiss.read_index('vectorized_data.faiss')
Немного неожиданно, что config/config.py наливает бд, но ладно

2024-11-14 08:40 UTC, stewkk commented on LLM/app/core/formalize/formalize.py
> +    time.sleep(1)
Это зачем?

2024-11-14 08:40 UTC, stewkk commented on LLM/app/core/vector_db/faiss_db.py
> +    Process the questions, optionally using saved vectorized data
Тут, кажется, докстринг устарел

2024-11-14 08:40 UTC, stewkk commented on LLM/app/core/vector_db/text_translator.py
> +        return cls._instance
Я не очень понимаю, зачем тут нужен синглтон. Он, например, не учитывает, что у конструктора есть аргумент `dest_lang`

2024-11-14 08:40 UTC, stewkk commented on LLM/app/utils/DB/Readme.md
😄

2024-11-14 08:51 UTC, BaldiSlayer commented on .github/workflows/images.yaml
> +    branches: [ "main", "impl-tgbot", "new-deploy" ]
это уберем перед мерджем, спасибо, что подсветил
оставил, потому что тещу из своей ветки)

2024-11-14 08:52 UTC, BaldiSlayer commented on LLM/app/core/formalize/formalize.py
> +    time.sleep(1)
я не знаю, это не мой код ж

2024-11-14 08:52 UTC, BaldiSlayer commented on LLM/app/core/formalize/formalize.py
> +    time.sleep(1)
это код Аркадия, на который я поребейзился

2024-11-14 08:53 UTC, BaldiSlayer commented on LLM/app/core/vector_db/text_translator.py
> +        return cls._instance
> В чем проблема несколько инстансов GoogleTranslator создавать?

а зачем они будут создаваться на каждый запрос новый?

2024-11-14 08:55 UTC, BaldiSlayer commented on chart/files/config.py
> +api_key = os.environ['MISTRAL_API_KEY']
надо удалить

2024-11-14 08:55 UTC, BaldiSlayer commented on LLM/app/core/formalize/formalize.py
> +        logger.info("Переформулированный вопрос: %s", refactored_question)
я этот код не трогал (

2024-11-14 09:02 UTC, stewkk commented on LLM/app/core/vector_db/faiss_db.py
> +        return cls._instance
Тут, как будто, тоже синглтон лишний. Зачем нам гарантировать один инстанс SentenceTransformer?

2024-11-14 09:03 UTC, stewkk commented on LLM/app/utils/create_embeddings.py
> +            item['question'] = item['question'].replace('\n', ' ')
> я уже успел усомниться в этом решении, просто подумал зачем нам нужны переносы строк из yaml)

А, ну в целом, согласен

2024-11-14 09:03 UTC, stewkk commented on LLM/app/core/formalize/formalize.py
> +    time.sleep(1)
Ок

2024-11-14 09:07 UTC, stewkk commented on LLM/app/core/vector_db/text_translator.py
> +        return cls._instance
Ну это как-то по-другому должно решаться, не синглтоном же =) Считай, что ты сделал глобальную переменную. Т.о. тебя зависимость от TextTranslator неявная и т.п. Можно тогда без класса Signleton делать просто глобальную переменную. Ну и не вижу проблемы создавать на каждый запрос новый объект

2024-11-17 09:36 UTC, stewkk approved these changes

2024-11-17 12:22 UTC, BaldiSlayer commented on LLM/app/routers/questions.py
> +    # TODO add reponse model for openapi
не буду

2024-11-17 12:22 UTC, merged