Рапота вопросы
BaldiSlayer/rofl-lab1 pull request #96
Opened 2024-11-11 19:55 UTC by massssha

2024-11-11 20:02 UTC, TonitaN requested changes
Дополнения, уточнения. И есть большое подозрение, что потом (после вливания и выбора метрики) эти ответы ещё придётся рефакторить и уточнять, т.к. очень много малоспецифических (если честно, думаю, на все эти вопросы текущая версия LLM и без нас ответит неплохо).

2024-11-11 20:02 UTC, TonitaN commented on data/data.yaml
> +    NP-полна ли проблема выполнимости булевых формул, которая заключается в вопросе,
Чуть-чуть переформулировать бы. Существуют ли значения переменных (в множестве True,False) такие, что формула при этих значениях принимает значение True

2024-11-11 21:18 UTC, BaldiSlayer commented on data/data.yaml
> +    Элемент a называется (непосредственным) последователем b, если a > b и не существует такого c, что a > c и c > b.
мб стоит сказать `элемента b` и то, что a, b и c из этого множества?

2024-11-14 07:39 UTC, BaldiSlayer commented on data/data.yaml
> +    Элемент a называется (непосредственным) предшественником b, если a < b и не существует такого c, что a < c и c < b.
Мне казалось, что я про это писал....
Видимо у меня уже шизофрения

Тут не надо случайно указать в ответе, что a, b, c, из этого упорядоченного множества?

2024-12-17 20:10 UTC, massssha commented
@TonitaN Добрый вечер, посмотрите, пожалуйста, изменения

2024-12-24 18:25 UTC, TonitaN approved these changes
Только добавить в самые короткие вопросы больше контекста

2024-12-24 18:25 UTC, TonitaN commented on data/data.yaml
> +    Какая грамматика называется неукорачивающей?
рискнула бы добавить в вопрос "в иерархии Хомского"

2024-12-24 18:25 UTC, TonitaN commented on data/data.yaml
> +    Какие множества называются вполне упорядоченными?
добавить "в теории порядков". Да, @BaldiSlayer , я начинаю перестраховываться после #165

2024-12-24 18:25 UTC, TonitaN commented on data/data.yaml
> +    Лемма Цорна (англ. Zorn's lemma)
лучше тоже - в теории порядков

2024-12-24 18:33 UTC, massssha commented
@TonitaN добрый вечер! Исправлено!

2024-12-24 18:37 UTC, BaldiSlayer commented
> @TonitaN добрый вечер! Исправлено!

После аппрува - ко мне идти над))

2024-12-24 18:40 UTC, TonitaN reviewed
Теперь осталось переделать под новый формат

2024-12-24 18:42 UTC, BaldiSlayer commented
> Теперь осталось переделать под новый формат

там легко, я кидал переделывающий скрипт в беседу группы в тг)

2024-12-24 19:28 UTC, merged