Якубов вопросы
BaldiSlayer/rofl-lab1 pull request #97
Opened 2024-11-12 18:46 UTC by papashik

2024-11-12 19:48 UTC, TonitaN requested changes
Исправляем косячки из викиконспектов ИТМО)

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    его грамматики неоднозначны. Если хотя бы одна грамматика языка L
Пояснить, что такое неоднозначная грамматика.

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    некоторое порождение вида S ⇒* αXβ ⇒* w, где w ∈ T*. Отметим, что X может
И Sigma плавно превратилась в элегантную Т

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    бесполезным. Очевидно, что исключение бесполезных символов из грамматики не
Пояснить, что такие символы могут быть недостижимыми (терминалы, нетерминалы) или непорождающими (нетерминалы)

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    Пусть Γ = ⟨N, Σ, P, S⟩ — КС-грамматика. Опиши алгоритм нахождения всех
Г или G?

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    1. Найти все ε-правила. Составить множество, состоящее из нетерминалов, входящих в левые части таких правил.
Обозначить это множество как-то

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    2. Воспользуемся алгоритмом устранения левой рекурсии. Получим грамматику, все
Пояснить про упорядочение нетерминалов.
Пояснить последнее преобразование.
Заменить дельта на другую греческую букву (дельты заняты под множества переходов у автоматов)

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    Контекстно-свободная грамматика G = ⟨N, Σ, P, S⟩ называется самоприменимой (англ. self-embeded), если ∃A ∈ N : A ⇒* αAβ, α≠ε ∧ β≠ε.
Я знаю, откуда этот термин (кстати, в английском - опечатка), но он мне категорически не нравится в русском варианте, потому что термин самоприменимость здесь расходится со всеми другими контекстами этого же термина. Поэтому лучше заменить на "что такое рекурсивный нетерминал".

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    выполнено перед вторым, иначе время нормализации ухудшится до O(2^|Γ|).
А что такое здесь размер грамматики? Расшифровать

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    могло появиться k−1 новых правил, причем их длина не превышает двух. На этом
Ну это неправда.
Контрпример:
S -> AAAAAAAAAAAAAAA
S -> a
Во сколько раз вырастет размер грамматики после удаления длинных правил?

2024-11-12 19:48 UTC, TonitaN commented on data/data.yaml
> +    4. существует A ∈ N, такой что S ⇒+ uAz ⇒+ uvAyz ⇒+ uvxyz. (т.е. ∀ k⩾0 u(v^k)x(y^k)z ∈ L)
Пояснить содержательно и связать с классической леммой о накачке для КС языков.

2024-11-14 02:55 UTC, TonitaN commented on data/data.yaml
> +    могло появиться k−1 новых правил, причем их длина не превышает двух. На этом
Ну тогда и надо говорить, как он считается. Т.к. обычно считается от числа правил.

2024-11-14 07:18 UTC, papashik commented on data/data.yaml
> +    могло появиться k−1 новых правил, причем их длина не превышает двух. На этом
Как считается размер - указал. Вы имеете в виду просто как число правил или как число правил, сложенное с числом символов в правой части правил вывода?

2024-11-14 07:26 UTC, BaldiSlayer commented on data/data.yaml
> +    Символ X называется полезным в грамматике Γ = ⟨N, Σ, P, S⟩, если существует
А что такое ⇒*?

2024-11-14 07:29 UTC, BaldiSlayer commented
Есть ощущение, что надо завести ещё файл с общепринятыми обозначениями, куда человек должен будет смотреть при написании вопросов, чтобы у всех все было одинаково...


(Паш, если что - это скорее для АН, чем для тебя)

2024-11-14 07:33 UTC, BaldiSlayer commented on data/data.yaml
> +    Сформулируй лемму Огдена в теории формальных языков.
Я бы убрал "в теории формальных языков"

И наверное можно если хочется - дописать:
для кс языков / для доква ксности языка / etc

2024-11-14 07:36 UTC, BaldiSlayer commented on data/data.yaml
> +    1. x содержит по меньшей мере одну помеченную позицию;
У меня есть тупой вопрос...
А что значит помечен?

2024-11-14 14:00 UTC, BaldiSlayer commented on data/data.yaml
> +    Доказательство: Построим МП-автомат для пересечения регулярного языка и
наверное есть смысл тут расшифровать что такое МП-автомат

2024-11-14 14:03 UTC, BaldiSlayer commented on data/data.yaml
> +    МП-автомат. Слово допускается этим автоматом ⟺ слово допускается и ДКА и
давай запишем ⟺, как `тогда и только тогда, когда`

2024-11-14 16:21 UTC, papashik commented on data/data.yaml
> +    Символ X называется полезным в грамматике Γ = ⟨N, Σ, P, S⟩, если существует
Означает, что существует такая цепочка, что данная строка выводима через неё (другими словами, обычная стрелка означает, что существует конкретное правило вывода A ⇒ B, а запись A ⇒* B означает, что может B и не выводима напрямую из А, но выводима например вот так: A ⇒ С, С ⇒ B)

Я могу пояснить это, но как будто это скорее общепринятое обозначение, чем конкретно для этого вопроса.

2024-11-17 12:10 UTC, papashik commented
@TonitaN Поправил все замечания, в т.ч. от Лёши Лисова, посмотрите, пожалуйста

2024-11-17 18:46 UTC, molivka commented on data/data.yaml
> +    Что такое неукорачивающаяся грамматика в теории формальных языков?
дубль @massssha «Какая грамматика называется неукорачивающей?»

2024-11-23 21:27 UTC, TonitaN approved these changes

2024-11-23 21:27 UTC, TonitaN commented on data/data.yaml
> +    Позицией в слове длины k назовем такое целое i, что 1 ≤ i ≤ k. Символ aзанимает
Тут у меня отображается какой-то мусор после буквы а

2024-11-30 19:57 UTC, BaldiSlayer commented on data/data.yaml
> +    Позицией в слове длины k назовем такое целое i, что 1 ≤ i ≤ k. Символ aзанимает
```suggestion
    Позицией в слове длины k назовем такое целое i, что 1 ≤ i ≤ k. Символ a занимает
```

2024-11-30 19:58 UTC, BaldiSlayer approved these changes

2024-11-30 19:59 UTC, BaldiSlayer commented
мерджу

2024-11-30 19:59 UTC, merged