Вопросы Проклашкина Софья
BaldiSlayer/rofl-lab1 pull request #98
Opened 2024-11-12 19:57 UTC by sprosonya

Добавила расшифровки к некоторым определениям, английские названия и дополнительные разъяснения

2024-11-13 00:53 UTC, TonitaN requested changes
Главная проблема - это накладки с соседними ответами. Про язык Дика рекомендую заменить на вопрос "является ли язык палиндромов регулярным" и использовать очень похожую схему обоснования, или же добавить другое доказательство нерегулярности языка Дика (через классы эквивалентности Майхилла-Нероде). Про бесполезные символы - интегрироваться с соседями, и добавить, что такие определения возможны в силу независимости переписывания нетерминала от контекста в КС-грамматиках. Что также делает проблему пустоты языка КС-грамматики разрешимой: язык грамматики непустой <=> стартовый нетерминал не является бесполезным, или, что эквивалентно, в грамматике есть хотя бы один порождающий и достижимый нетерминал. В КЗ-грамматиках достижимость и продуктивность нетерминалов имеют смысл лишь в определённых контекстах этих нетерминалов, из-за чего вопрос пустоты языка в таких грамматиках неразрешим.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    4. Правила продукции (P) (англ. production rules или productions): Набор правил, определяющих, как нетерминальные символы могут быть заменены на терминальные или другие нетерминальные символы. Ка
Переменной в голове - не по-русски получилось. Нетерминала в левой части правила - ок.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    4. Правила продукции (P) (англ. production rules или productions): Набор правил, определяющих, как нетерминальные символы могут быть заменены на терминальные или другие нетерминальные символы. Ка
И лучше здесь заменить переменные на нетерминалы, т.к. речи о связи с TRS пока нет.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Является ли множество цепочек сбалансированных скобок регулярным языком?
Это чистый дубль ответа @BaldiSlayer , придётся заменить на что-то.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +  answer: >
Ну это опять почти чистый дубль @papashik в вопросе. Лучше бы объединить ваши два ответа в один.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Крона дерева разбора (англ. leaves of the parse tree) - множество терминальных символов, упорядоченное в соответствии с номерами их достижения при обходе дерева в глубину из корня. Крона дерева р
https://en.wikipedia.org/wiki/Terminal_yield
Обычно именно yield я в статьях и видела. Лучше добавить синонимы.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Существуют языки, которые можно задать одновременно как однозначными, так и неоднозначными грамматиками. Однако, есть контекстно-свободные языки, для которых не существует однозначных контекстно-
По опыту соседней группы, не лишне также добавить пояснение, что недетерминированные языки могут быть выводимы однозначной грамматикой (например, язык палиндромов), но если язык существенно неоднозначен, то он заведомо не является детерминированным.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Здесь A, B, C, D — нетерминалы, a a — терминал.
Добавить, что речь про контекстно-зависимые грамматики, и описать, к чему сводится НФ Куроды, если рассматривать КС-грамматики.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Также грамматику Пенттонена называют односторонней нормальной формой (англ. one-sided normal form). Она является частным случаем нормальной формы Куроды: когда A = C в первом правиле определения.
Опять уточнить контекст и объяснить, что получается при переходе к КС-грамматике.

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Когда контекстно-свободная грамматика не содержит бесполезных нетерминалов?
Опять согласовать с @papashik

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Использование нормальной формы Грейбах позволяет доказать, что для каждого контекстно-свободного языка (не содержащего ε) существует автомат с магазинной памятью без переходов по ε, а также позво
забыли "распознающий тот же язык"
И про линейную сложность - увы, нет. Число шагов в итоговом дереве разбора будет линейно, но их ещё надо найти, поэтому можно сказать, что недетерминированный алгоритм будет линейным, а детерминированный может потребовать ещё дополнительных структур для обработки возвратов (довольно точная аналогия здесь - НКА без эпсилон-переходов).
Но метод рекурсивного спуска да, использовать можно (стоит ещё сказать, что это удобно, потому что в ГНФ никогда не бывает левой рекурсии)

2024-11-13 00:53 UTC, TonitaN commented on data/data.yaml
> +    Класс 3: К третьему типу относятся автоматные или регулярные грамматики (англ. regular grammars) — самые простые из формальных грамматик, которые задают регулярные языки. Они являются контекстно-
Тут забыли сказать, что они распознаются конечными автоматами.

2024-11-13 22:30 UTC, sprosonya commented
@TonitaN, добрый вечер!
Поправила все ваши замечания
Вопросы, которые совпадали с @papashik, мы объединили и добавили к нему мою информацию
Вопрос, совпадающий с @BaldiSlayer, я заменила на предложенный вами

2024-11-14 07:12 UTC, BaldiSlayer commented on data/data.yaml
> +    Используем лемму о накачке (англ. pumping lemma) для доказательства. Пусть язык палиндромов регулярен и n - соответствующая константа из теоремы. Рассмотрим в языке такие палиндромы w = a^nba^n.
Может напишем не 
> n - соответствующая константа

А
> n - длина накачки


?

2024-11-14 07:13 UTC, BaldiSlayer commented on data/data.yaml
> +    Польза нормальной формы Хомского (CNF) в следующих аспектах:
Я бы тут наверное написал не CNF, а полностью расшифровал

2024-11-14 07:20 UTC, BaldiSlayer commented on data/data.yaml
> +    Грамматика представлена в нормальной форме Грейбах (GNF) (англ. Greibach normal form), если каждое ее правило имеет вид A_i → a_j α, где A_i ∈ N, α ∈ N*, a_j ∈ Σ.
Кстати, нам точно нужны тут индексы, можем как-то словами покрыть то, что нам дают индексы? Хотелось бы избавиться от них

2024-11-14 07:21 UTC, BaldiSlayer commented on data/data.yaml
> +    Грамматика представлена в нормальной форме Грейбах (GNF) (англ. Greibach normal form), если каждое ее правило имеет вид A_i → a_j α, где A_i ∈ N, α ∈ N*, a_j ∈ Σ.
И го хотя бы один раз напишем внизу что такое epsilon?

А мб лучше даже везде заменить на пустое слово

2024-11-14 07:22 UTC, BaldiSlayer commented on data/data.yaml
> +    Грамматика представлена в нормальной форме Грейбах (GNF) (англ. Greibach normal form), если каждое ее правило имеет вид A_i → a_j α, где A_i ∈ N, α ∈ N*, a_j ∈ Σ.
И сейчас будет очень душно:
> может потребовать дополнительных структур

Здесь же имелось в виду структур данных?
Давай тогда слово данных тоже напишем, иначе без контекста не оч понятно, что за структуры

2024-11-14 11:10 UTC, sprosonya commented
Поправила Лешины комментарии и сама еще добавила разных синонимов и переводов терминов :)

2024-11-23 21:36 UTC, TonitaN requested changes
Требуются дальнейшие уточнения

2024-11-23 21:36 UTC, TonitaN commented on data/data.yaml
> +      - по каждому переходу вида (q, t, A) → (p, A_1 . . . A_n) добавим правила для всех возможных q_i вида [q, A, q_n] → t[p, A_1, q_1]...[q_n−1, A_n, q_n]
Тут нужно больше словесных пояснений, разве эта конструкция понятна без них просто в виде формулы? Как минимум пояснить физический смысл имён  нетерминалов.

2024-11-23 21:36 UTC, TonitaN commented on data/data.yaml
> +    Существенно неоднозначные грамматики всегда выводят недетерменированный язык, однако недетерменированный язык может быть задан однозначной грамматикой (например, язык палиндромов)
недетерминированный

2024-11-23 21:36 UTC, TonitaN commented on data/data.yaml
> +    Здесь A, B, C, D — нетерминалы, a a — терминал.
А как же пустые правила и цепные правила? Разве они могут встретиться в ХНФ?

2024-11-23 21:36 UTC, TonitaN commented on data/data.yaml
> +    Также грамматику Пенттонена называют односторонней нормальной формой (англ. one-sided normal form). Она является частным случаем нормальной формы Куроды: когда A = C в первом правиле определения.
Баг с эпсилон-правилами остался.

2024-11-29 10:30 UTC, sprosonya commented on data/data.yaml
> +    Используем лемму о накачке (англ. pumping lemma) для доказательства. Пусть язык палиндромов регулярен и n - соответствующая константа из теоремы. Рассмотрим в языке такие палиндромы w = a^nba^n.
Писала ответ на этот вопрос, опираясь на Хопкрофта
В главе 5.1.1 стр.186 (Контекстно-свободные грамматики и языки) указано доказательство для палиндромов в алфавите {0,1}
<img width="803" alt="Снимок экрана 2024-11-29 в 12 54 08" src="https://github.com/user-attachments/assets/3606716a-5fc9-46d1-a4bf-dbe06d312a11">
Можете, пожалуйста, подсказать, в каком направлении стоит искать ошибку в моем ответе?
Может быть, стоит пояснить, почему в y будет одна или несколько a из первой группы?

2024-11-29 11:38 UTC, TonitaN commented on data/data.yaml
> +    Используем лемму о накачке (англ. pumping lemma) для доказательства. Пусть язык палиндромов регулярен и n - соответствующая константа из теоремы. Рассмотрим в языке такие палиндромы w = a^nba^n.
Простите, увидела, что неправа я. У железного друга иногда область xz объявляется областью накачки, и я невнимательно посмотрела, что у вас это всё слово. Виновата.

2024-12-01 21:15 UTC, sprosonya commented
@TonitaN Добрый вечер! Постаралась все поправить, посмотрите, пожалуйста

2024-12-02 14:17 UTC, TonitaN requested changes
Уже почти всё, но есть ещё маленькие неточности.

2024-12-02 14:17 UTC, TonitaN commented on data/data.yaml
> +        Такие продукции гласят, что один из путей выталкивания A и перехода из состояния q в состояние q_k заключается в том, чтобы прочитать t, затем использовать некоторый вход для выталкивания A_1
r_1 и r_2 не определены, должны быть q_1 и q_2, и лучше, поскольку второй переход словами объяснён, добавить его и в правую часть правила.

2024-12-02 14:17 UTC, TonitaN commented on data/data.yaml
> +    4. A → a.
В НФ Куроды могут быть эпсилон-правила, но их не может быть в НФ Хомского.
Т.е. НФ Хомского - это НФ Куроды, в которой нет эпсилон-правил кроме как для стартового нетерминала, нет левых частей длины 2, и нет цепных правил.

Аналогично нужно уточнить по Пенттонену.

2024-12-08 12:48 UTC, BaldiSlayer commented
убери из `pr` файл `.md` плз, нам это уже не нужно, он сам сгенерится в `CI`

2024-12-12 13:14 UTC, TonitaN approved these changes

2024-12-12 13:51 UTC, BaldiSlayer approved these changes
ок

2024-12-12 13:52 UTC, merged