вопросы Пенкин Артём
BaldiSlayer/rofl-lab1 pull request #99
Opened 2024-11-13 14:08 UTC by ssairu

@TonitaN

переотправка данных из data.json

2024-11-13 20:27 UTC, BaldiSlayer commented on data/data.yaml
> +    Существует алгоритм, позволяющий по произвольной контекстно-свободной грамматике G узнать, верно ли, что ε ∈ L(G). Существует алгоритм, позволяющий по произвольной контекстно-свободной грамматике
сло-ву -> слову

2024-11-13 20:29 UTC, BaldiSlayer commented on data/data.yaml
> +    Существует алгоритм, позволяющий по произвольной контекстно-свободной грамматике G узнать, верно ли, что L(G) = ∅.
давай L(G) = ∅ напишем словами

2024-11-14 03:01 UTC, TonitaN requested changes
Очень неконкретные ответы, мало контекста, нужно сильно расширять и дополнять, чтобы не ухудшить поведение LLM.

2024-11-14 03:01 UTC, TonitaN commented on data/data.yaml
> +    Класс языков, порождаемых неукорачивающими грамматиками, замкнут относительно операций объединения, пересечения и дополнения.
Повторить, что речь о КЗ-языках, и сравнить с другими классами. Пояснить про незамкнутость относительно морфизмов.

2024-11-17 19:23 UTC, molivka commented on data/data.yaml
> +    Когда разрешима проблема равентства автоматных языков в теории формальных языков?
уже есть, @NailorSH «Как проверяется равенство языков двух детерминированных конечных автоматов (сокр. ДКА)?»

2024-11-17 19:26 UTC, molivka commented on data/data.yaml
> +    Каждая контекстная грамматика является неукорачивающей. Каждая неукорачивающая грамматика эквивалентна некоторой контекстной грамматике.
похоже на дубль @massssha «Какая грамматика называется неукорачивающей?»

2025-01-18 19:56 UTC, closed without merging